#!/usr/bin/bash
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/core.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./setup.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./paramset_pyspecdata/__init__.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/version.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/__init__.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/nnls.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./setup_paramset.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/ndshape.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/plot_funcs/image.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/plot_funcs/__init__.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/datadir.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/figlist.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/fornotebook.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/ipy.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/fourier/ftshift.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/fourier/ft.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/fourier/ft_shift.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/fourier/ift.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/fourier/convolve.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/fourier/shear.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/fourier/_ft_conj.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/fourier/__init__.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/load_files/__init__.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/load_files/bruker_esr.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/load_files/open_subpath.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/load_files/bruker_nmr.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/general_functions.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./doc/conf.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/axis_manipulation/__init__.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/axis_manipulation/inhomog_coords.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/axis_manipulation/register_axis.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/axis_manipulation/secsy.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/axis_manipulation/shear.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/latexscripts.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/units.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./install_gui.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./demos/NNLS_Tikhonov_190104.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./demos/nddata_NNLS_Tikhonov_190104.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./lapack-3.4.0/lapack_testing.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./notebook/foraudrey_dnp_code.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./notebook/forgui.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./notebook/standalone_compilation.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./notebook/standalone_example.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/load_files/acert.py
2to3.exe -n -f all -f idioms -f set_literal -f buffer -w ./pyspecdata/load_files/prospa.py
