# the following are generated with:
# git diff --name-status local_public..public | egrep "^D"
git rm 090601notebook.tex
git rm 090602h2oemax4.pdf
git rm 090602h2oemax5.pdf
git rm 090602h2oemax7.pdf
git rm 090604notebook.tex
git rm 090608h2o10.pdf
git rm 090608h2o11.pdf
git rm 090608h2o12.pdf
git rm 090608h2o14.pdf
git rm 090608h2o15.pdf
git rm 090608h2o16.pdf
git rm 090608h2o17.pdf
git rm 090608h2o18.pdf
git rm 090608h2o7.pdf
git rm 090608h2o8.pdf
git rm 090608h2o9.pdf
git rm 090608notebook.tex
git rm 090609notebook.tex
git rm 090623notebook.tex
git rm 090630notebook.tex
git rm 090703notebook.tex
git rm 090714e_v_field.pdf
git rm 090714notebook.tex
git rm 090721notebook.tex
git rm 090724notebook.tex
git rm 090725checkfield.pdf
git rm 090725emax1.pdf
git rm 090725franck.pdf
git rm 090725franck2.pdf
git rm 090725franck3.pdf
git rm 090725franck4.pdf
git rm 090730notebook.tex
git rm 090730withravi.pdf
git rm 090731emax1.pdf
git rm 090731emax2.pdf
git rm 090731emax3.pdf
git rm 090731emax4.pdf
git rm 090803notebook.tex
git rm 090805nonlinearity1.pdf
git rm 090805nonlinearity2.pdf
git rm 090805nonlinearity3.pdf
git rm 090805nonlinearity4.pdf
git rm 090805nonlinearity4.png
git rm 090805nonlinearity5.pdf
git rm 090805nonlinearity5.png
git rm 090805nonlinearity6.pdf
git rm 090805nonlinearity6.png
git rm 090807commercial.png
git rm 090807commercial2.png
git rm 090807commercial_shifting.png
git rm 090807cyl_nosample.png
git rm 090807cyl_wsample.png
git rm 090807emax1.pdf
git rm 090807emax2.pdf
git rm 090810mailtocraig.pdf
git rm 090810notebook.tex
git rm 090811patriciaupdate.tex
git rm 090812cyl_refl1.png
git rm 090812cyl_wobb1.png
git rm 090812emax1.pdf
git rm 090812emax1_t.pdf
git rm 090812emax2_t.pdf
git rm 090812emax3.pdf
git rm 090812emax3_t.pdf
git rm 090812rect_tune.png
git rm 090812rect_tune2.png
git rm 090813copperfoiltest.pdf
git rm 090813copperfoiltest2.pdf
git rm 090813copperfoiltest_refl1.pdf
git rm 090813copperfoiltest_refl_verify.pdf
git rm 090813emax1.pdf
git rm 090821emax.pdf
git rm 090825emax1.pdf
git rm 090825emax1_t.pdf
git rm 090825emax2.pdf
git rm 090825emax2_t.pdf
git rm 090825notebook.tex
git rm 090827emax1.pdf
git rm 090827emax1_t.pdf
git rm 090827emax2.pdf
git rm 090827emax2_t.pdf
git rm 090827emax3.pdf
git rm 090827emax3_t.pdf
git rm 090827emax4.pdf
git rm 090827emax4_t.pdf
git rm 090827emax5.pdf
git rm 090827emax5_t.pdf
git rm 090902fornaveed.tex
git rm 090902notebook.tex
git rm 090914notebook.tex
git rm 090924notebook.tex
git rm 091001notebook.tex
git rm 091020notebook.tex
git rm 091027notebook.tex
git rm 160firstpeak.png
git rm 160firstpeak_sample.png
git rm 160secondpeak.png
git rm 160secondpeak_sample.png
git rm 160wobb.png
git rm 165wobb.png
git rm 169_5wobb.png
git rm AC/SO_saturation_3lines-small.pdf
git rm AC/SO_saturation_3lines.pdf
git rm AC/SO_saturation_3lines.svg
git rm AC/T2_echoes_sideplot-1.pdf
git rm AC/achemso_local.cls
git rm AC/actively_cancelled_esr.tex
git rm AC/actively_cancelled_esr_old.tex
git rm AC/delay_waveform_algorithm.pdf
git rm AC/library_abbrev.bib
git rm AC/mybasiccomments.sty
git rm AC/mycomments.sty
git rm AC/mydefs.sty
git rm AC/myhyperref.sty
git rm AC/mylabels.sty
git rm AC/nutation_with_pulses.pdf
git rm AC/songi_email_130922.txt
git rm ACERT_hardware/CRNL-TPR_95-1.pdf
git rm ACERT_hardware/dielectric_sandwich_140115.svg
git rm ACERT_hardware/pressure_cell_140516.svg
git rm ACERT_hardware/sample_rings.svg
git rm ACERT_hardware/sapphire_sample_holder.fcstd
git rm ACERT_hardware/simplecone_edited_140411.svg
git rm ACERT_hardware/taper_edited_140411.svg
git rm ACERT_hardware/teflon_assembly140217.svg
git rm ACERT_hardware/teflon_container.FCStd
git rm ACERT_hardware/teflon_container.FCStd1
git rm ACERT_hardware/teflon_membrane140217.svg
git rm EF_loop_data.txt
git rm HCl_model.txt
git rm HFSS/150um_sapphire_140506.jpg
git rm HFSS/150um_sapphire_140506_edited.svg
git rm HFSS/50um_sapphire_140506.jpg
git rm HFSS/50um_sapphire_140506_edited.svg
git rm HFSS/50um_sapphire_control_140506.jpg
git rm HFSS/H_direction_for_sameh.svg
git rm HFSS/Helix.hfss
git rm HFSS/Lenses_140730.hfss
git rm HFSS/Lenses_box_140730.hfss
git rm HFSS/Lenses_wcoating_141010.hfss
git rm HFSS/Lenses_wcoating_141024.hfss
git rm HFSS/SCALE_131022.vbs
git rm HFSS/assign_coax_ports131018.vbs
git rm HFSS/change_material.vbs
git rm HFSS/coax.hfss
git rm HFSS/coax.vbs
git rm HFSS/corrugated_141027.hfss
git rm HFSS/corrugated_141027.jpg
git rm HFSS/corrugated_141027.py
git rm HFSS/corrugated_taper_141028.hfss
git rm HFSS/cylinder_with_var_len.vbs
git rm HFSS/diel_resonator_140526.hfss
git rm HFSS/diel_winner_empty_141111.hfss
git rm HFSS/diel_winner_shield_141111.hfss
git rm HFSS/export_EB.py
git rm HFSS/export_zxplane.vbs
git rm HFSS/fabry_perot131116.hfss
git rm HFSS/fabry_perot131116_bak.hfss
git rm HFSS/fabry_perot131116_mycomp.hfss
git rm HFSS/fabry_perot131119.hfss
git rm HFSS/fabry_perot131119_adjust.hfss
git rm HFSS/fabry_perot131122_eigenreduced.hfss
git rm HFSS/fabry_perot131205.hfss
git rm HFSS/fabry_perot131206.hfss
git rm HFSS/fabry_perot131206_distsweep.hfss
git rm HFSS/fabry_perot131207_freqsweep.hfss
git rm HFSS/fields.clc
git rm HFSS/geometry_export.vbs
git rm HFSS/grab_enclosure.vbs
git rm HFSS/helix_131021.py
git rm HFSS/helix_131021.vbs
git rm HFSS/helix_141113.hfss
git rm HFSS/helix_bothopen_141114.hfss
git rm HFSS/helix_plate_131022.vbs
git rm HFSS/helix_wider_141114.hfss
git rm HFSS/helix_widercontainer_smallcoil_141117.hfss
git rm HFSS/helix_widercontainer_smallcoil_lowpitch_141117.hfss
git rm HFSS/high_impedance_cylinder.hfss
git rm HFSS/mesh_131115.py
git rm HFSS/mesh_131204.py
git rm HFSS/mesh_and_sapphire_140523.hfss
git rm HFSS/mesh_only_131209.hfss
git rm HFSS/mesh_only_131209.py
git rm HFSS/mesh_only_131209_changemesh.hfss
git rm HFSS/mesh_only_131210_changemesh.hfss
git rm HFSS/mesh_only_131213_withdiel_workup.hfss
git rm HFSS/mesh_only_131213_withdiel_workup_magH.jpg
git rm HFSS/mesh_only_131213_withdiel_xz.fld
git rm HFSS/mesh_only_131213_withdiel_xz_mesh.fld
git rm HFSS/mesh_only_131213_withdiel_xz_sapphire.fld
git rm HFSS/mesh_only_131216_lossydiel.hfss
git rm HFSS/mesh_only_131219_movediel.hfss
git rm HFSS/mesh_only_131219_movediel_magH.jpg
git rm HFSS/mesh_only_140120_dielthickness.hfss
git rm HFSS/mesh_only_140124_dielthickness_smaller.hfss
git rm HFSS/mesh_only_140128_smallFEM.hfss
git rm HFSS/mesh_only_140129.hfss
git rm HFSS/mesh_only_140129.py
git rm HFSS/mesh_only_140204.hfss
git rm HFSS/mesh_wsapphire_140129.hfss
git rm HFSS/mesh_wsapphire_140204.hfss
git rm HFSS/microcoil_eigen131028.hfss
git rm HFSS/myHFSS.py
git rm HFSS/my_coax.hfss
git rm HFSS/new_coax.py
git rm HFSS/new_coax.vbs
git rm HFSS/new_sample_container_130121.svg
git rm HFSS/optim_tee.hfss
git rm HFSS/pml_rectangle.hfss
git rm HFSS/quartz_watertest_141110.hfss
git rm HFSS/resonator_140521.hfss
git rm HFSS/resonator_fsweep_140522.hfss
git rm HFSS/sameh_question_140110.svg
git rm HFSS/sapphire_expmatch_140505.hfss
git rm HFSS/sapphire_expmatch_control_140505.hfss
git rm HFSS/sapphire_samehvalues_140507.hfss
git rm HFSS/sapphire_samehvalues_140507.jpg
git rm HFSS/sapphire_watertest_141110.hfss
git rm HFSS/sapphire_watertest_surrsaph_141110.hfss
git rm HFSS/sapphire_wcircularconductor_140429.hfss
git rm HFSS/sapphire_wconductor_140218.hfss
git rm HFSS/sapphire_wconductor_140427.hfss
git rm HFSS/sapphire_wno_conductor_140218.hfss
git rm HFSS/sapphire_wone_conductor_140218.hfss
git rm HFSS/sapphire_wsmallercircularconductor_140429.hfss
git rm HFSS/sapphonly_140210.hfss
git rm HFSS/sapphonly_control_140210.hfss
git rm HFSS/sapphonly_large_140213.hfss
git rm HFSS/sapphonly_large_halfwave_140214.hfss
git rm HFSS/sapphonly_large_quarterwave_140214.hfss
git rm HFSS/screenshot_131028.png
git rm HFSS/set_stack_to_poynting140128.vbs
git rm HFSS/smooth_bore_141023.hfss
git rm HFSS/smooth_bore_141023.jpg
git rm HFSS/taper_131022.py
git rm HFSS/taper_141028.py
git rm HFSS/taper_for_sameh_140323.hfss
git rm HFSS/tee.hfss
git rm HFSS/tee.vbs
git rm HFSS/tee2.vbs
git rm HFSS/tee_optim.vbs
git rm HFSS/temp.vbs
git rm HFSS/waveguide.hfss
git rm HFSS/wg_combiner.hfss
git rm IEEEtran.bst
git rm Latex2wiki.py
git rm OpenGl/PythonOpenGLWaterMol.py
git rm OpenGl/Texturemap0.jpg
git rm OpenGl/Texturemap1.jpg
git rm OpenGl/Texturemap2.jpg
git rm OpenGl/chemistry.py
git rm OpenGl/demo_phong.py
git rm OpenGl/demo_texture.py
git rm OpenGl/euclid.py
git rm OpenGl/mayavi_demo.py
git rm OpenGl/mayavi_surface.py
git rm OpenGl/shader.py
git rm OpenGl/visvis_example.py
git rm OpenGl/visvis_shading.py
git rm OpenGl/visvis_surface.py
git rm Qt/gl_test.py
git rm Qt/qt_mpl_bars.py
git rm Qt/qt_sine_wave.pyw
git rm Qt/thread_example.py
git rm TMM_for_trisha.ipynb
git rm acert_hdf5.py
git rm achemso_local.cls
git rm address.txt
git rm alex_letter.tex
git rm alex_list.tex
git rm allratios.tex
git rm allratios.texp
git rm asymptote/GaussianSurface.asy
git rm asymptote/SierpinskiSponge.asy
git rm asymptote/arrows3.asy
git rm asymptote/curvedlabel3.asy
git rm asymptote/cyclohexane.asy
git rm asymptote/elevation.asy
git rm asymptote/flowchartdemo.asy
git rm asymptote/physicalpicture.asy
git rm asymptote/physicalpicture_minimal.asy
git rm asymptote/water.asy
git rm asymptote/water.pdf
git rm au_progs/USBm.dll
git rm au_progs/USBmAPI.h
git rm au_progs/au_progs_cnsi120917/jf.h
git rm au_progs/au_progs_cnsi120917/jf_basic
git rm au_progs/au_progs_cnsi120917/jf_basic.c
git rm au_progs/au_progs_cnsi120917/jf_dnp
git rm au_progs/au_progs_cnsi120917/jf_dnp.ourlab
git rm au_progs/au_progs_cnsi120917/jf_dnp1t1
git rm au_progs/au_progs_cnsi120917/jf_dnpconf
git rm au_progs/au_progs_cnsi120917/jf_dnplog
git rm au_progs/au_progs_cnsi120917/jf_dnpmult
git rm au_progs/au_progs_cnsi120917/jf_fastks
git rm au_progs/au_progs_cnsi120917/jf_lightbulb
git rm au_progs/au_progs_cnsi120917/jf_newexp
git rm au_progs/au_progs_cnsi120917/jf_newtest
git rm au_progs/au_progs_cnsi120917/jf_setdigatt
git rm au_progs/au_progs_cnsi120917/jf_setdigatt.bak
git rm au_progs/au_progs_cnsi120917/jf_setdigatt.ourlab
git rm au_progs/au_progs_cnsi120917/jf_setdigret
git rm au_progs/au_progs_cnsi120917/jf_setmw
git rm au_progs/au_progs_cnsi120917/jf_setmw.bak
git rm au_progs/au_progs_cnsi120917/jf_showplot
git rm au_progs/au_progs_cnsi120917/jf_t10
git rm au_progs/au_progs_cnsi120917/jf_t10.ourlab
git rm au_progs/au_progs_cnsi120917/jf_t10s
git rm au_progs/au_progs_cnsi120917/jf_test
git rm au_progs/au_progs_cnsi120917/jf_testcmd
git rm au_progs/au_progs_cnsi120917/jf_testftd.c
git rm au_progs/au_progs_cnsi120917/jf_testwrite
git rm au_progs/au_progs_cnsi120917/jf_usbonoff.h
git rm au_progs/au_progs_cnsi120917/john_lightbulb.cpp
git rm au_progs/au_progs_cnsi120917/john_lightbulb.obj
git rm au_progs/au_progs_cnsi120917/john_lightbulb_onoff.cpp
git rm au_progs/au_progs_cnsi120917/john_lightbulb_onoff.obj
git rm au_progs/au_progs_cnsi120917/john_lightobject.cpp
git rm au_progs/au_progs_cnsi120917/john_lightobject.obj
git rm au_progs/au_progs_cnsi120917/john_lightobjectuser.cpp
git rm au_progs/au_progs_cnsi120917/john_lightobjectuser.obj
git rm au_progs/digatt_ftdi.c
git rm au_progs/digatt_ftdi.h
git rm au_progs/ftd2xx.dll
git rm au_progs/ftd2xx.h
git rm au_progs/ftd2xx.lib
git rm au_progs/instrument_server.py
git rm au_progs/jf.h
git rm au_progs/jf_basic
git rm au_progs/jf_basic.c
git rm au_progs/jf_dnp
git rm au_progs/jf_dnp.bak130410
git rm au_progs/jf_dnp.ourlab
git rm au_progs/jf_dnp1t1
git rm au_progs/jf_dnp_backup
git rm au_progs/jf_dnpconf
git rm au_progs/jf_dnplog
git rm au_progs/jf_dnpmult
git rm au_progs/jf_fastks
git rm au_progs/jf_lightbulb
git rm au_progs/jf_newexp
git rm au_progs/jf_newtest
git rm au_progs/jf_setdigatt
git rm au_progs/jf_setdigatt.bak
git rm au_progs/jf_setdigatt.ourlab
git rm au_progs/jf_setdigret
git rm au_progs/jf_setmw
git rm au_progs/jf_setmw.bak
git rm au_progs/jf_setmwandT
git rm au_progs/jf_setmwandT.bak
git rm au_progs/jf_showplot
git rm au_progs/jf_t10
git rm au_progs/jf_t10.ourlab
git rm au_progs/jf_t10s
git rm au_progs/jf_test
git rm au_progs/jf_test.out
git rm au_progs/jf_testcmd
git rm au_progs/jf_testftd.c
git rm au_progs/jf_testwrite
git rm au_progs/jf_usbonoff.h
git rm au_progs/john_lightbulb.cpp
git rm au_progs/john_lightbulb_onoff.cpp
git rm au_progs/john_lightobject.cpp
git rm au_progs/john_lightobjectuser.cpp
git rm au_progs/ks_dnp
git rm au_progs/makeau
git rm au_progs/our_lab/jf_setmwpower.c
git rm au_progs/our_lab/jf_setmwpower_README.txt
git rm au_progs/test.c
git rm bargraph_3dexample.py
git rm blavatnik/CV.docx
git rm blavatnik/Franck_John_nominator_rationale.docx
git rm blavatnik/candidate_info.docx
git rm blavatnik/cv.txt
git rm blavatnik/nominator_rationale.txt
git rm blavatnik/research_statement.tex
git rm blavatnik/summary_figure.svg
git rm block_diagram.png
git rm bruker1.tex
git rm calcposition.py
git rm catalog.py
git rm circuit_layout.pdf
git rm cnsi/00001.jpg
git rm cnsi/"DNP Setup_forfanucci_jf.xls"
git rm cnsi/"DNP Setup_ml.xls"
git rm cnsi/DNP_power_supples_jf.xls
git rm cnsi/Hardware_status.pdf
git rm cnsi/Hardware_status.svgz
git rm cnsi/LabJackPython
git rm cnsi/attenuator_quote.doc
git rm cnsi/boxsheet.pdf
git rm cnsi/boxsheet.svgz
git rm cnsi/digatt_ftdi
git rm cnsi/digatt_ftdi.c
git rm cnsi/digatt_ftdi.h
git rm cnsi/env.sh
git rm cnsi/exodriver
git rm cnsi/faraday_cage.svgz
git rm cnsi/final_waveguide_plate.pdf
git rm cnsi/ftd2xx.dll
git rm cnsi/ftd2xx.h
git rm cnsi/ftd2xx.lib
git rm cnsi/ground_shield_in_place.svg
git rm cnsi/hmc591lp5.pdf
git rm cnsi/jf.h
git rm cnsi/jf_basic
git rm cnsi/jf_basic.c
git rm cnsi/jf_newtest
git rm cnsi/jf_setdigatt
git rm cnsi/jf_setdigatt.bak
git rm cnsi/jf_setmw
git rm cnsi/jf_setmw.bak
git rm cnsi/jf_test
git rm cnsi/jf_testftd.c
git rm cnsi/layout.pdf
git rm cnsi/layout.svg
git rm cnsi/layout_ready.svgz
git rm cnsi/linux-labjack.tar.gz
git rm cnsi/linux-labjack/COPYING
git rm cnsi/linux-labjack/"Function Status"
git rm cnsi/linux-labjack/INSTALL
git rm cnsi/linux-labjack/README
git rm cnsi/linux-labjack/driver/linux-2.4/Makefile
git rm cnsi/linux-labjack/driver/linux-2.4/labjack.c
git rm cnsi/linux-labjack/driver/linux-2.6/Makefile
git rm cnsi/linux-labjack/driver/linux-2.6/labjack.c
git rm cnsi/linux-labjack/liblabjack/Makefile
git rm cnsi/linux-labjack/liblabjack/ljackul.c
git rm cnsi/linux-labjack/liblabjack/ljackul.h
git rm cnsi/linux-labjack/test/Makefile
git rm cnsi/linux-labjack/test/analog-outs.c
git rm cnsi/linux-labjack/test/firmware-revision.c
git rm cnsi/linux-labjack/test/list-all.c
git rm cnsi/makeau
git rm cnsi/makeau.new
git rm cnsi/new_components.jpg
git rm cnsi/new_inside.jpg
git rm cnsi/new_probe_piece_v2.svg
git rm cnsi/new_probe_pieces.svgz
git rm cnsi/newprobe_100629_parts.png
git rm cnsi/newprobe_assembly.gif
git rm cnsi/newprobe_parts.gif
git rm cnsi/old_components.jpg
git rm cnsi/old_inside.jpg
git rm cnsi/output.pdf
git rm cnsi/p1010132.jpg
git rm cnsi/p1010133.jpg
git rm cnsi/p1010134.jpg
git rm cnsi/pastedpic_08232010_164839.png
git rm cnsi/power_meter_scope_quote.pdf
git rm cnsi/probe_airflow_tube.png
git rm cnsi/probe_airflow_tube.svg
git rm cnsi/probe_noise_idea.jpg
git rm cnsi/probetemplate.svg
git rm cnsi/probev2parts.jpg
git rm cnsi/problem.jpg
git rm cnsi/saddle_coil.svg
git rm cnsi/stdafx.h
git rm cnsi/targetver.h
git rm cnsi/waveguide_diagram.AD_DRW
git rm cnsi/waveguide_diagram.dwg
git rm cnsi/waveguide_diagram.dxf
git rm cnsi/waveguide_diagram.emf
git rm cnsi/waveguide_diagram.jpg
git rm cnsi/waveguide_diagram.pdf
git rm cnsi/waveguide_plate5.AD_PRT
git rm cnsi/waveguide_plate5.jpg
git rm cnsi/waveguide_plate5.pdf
git rm codeprint.tex
git rm comment_functions.py
git rm comments_example.tex
git rm construct_unit_matrices.py
git rm cpmg/100mM_fits.svg
git rm cpmg/100mM_fits_mod.svg
git rm cpmg/abstract.txt
git rm cpmg/amplitude_multiexp_slowT2_onlynew130228.svg
git rm cpmg/application.svg
git rm cpmg/author_agreement.doc
git rm cpmg/binary.dem
git rm cpmg/compare_for_review.pdf
git rm cpmg/cover_letter.docx
git rm cpmg/cover_letter.htm
git rm cpmg/cpmg.css
git rm cpmg/cpmg.html
git rm cpmg/cpmg.tex
git rm cpmg/cpmg0x.png
git rm cpmg/cpmg130301.dat
git rm cpmg/cpmg1x.png
git rm cpmg/cpmg2.html
git rm cpmg/highlights.docx
git rm cpmg/highlights.htm
git rm cpmg/library_abbrev.bib
git rm cpmg/mydefs.sty
git rm cpmg/mytest.dem
git rm cpmg/mytest2.dem
git rm cpmg/phantom.svg
git rm cpmg/pulse_sequence.svg
git rm cpmg/reply.tex
git rm cpmg/reviewers.docx
git rm cpmg/reviewers.htm
git rm cpmg/signal.svg
git rm cpmg/testshading.dem
git rm cpmg/toc.svg
git rm crif100105.pdf
git rm crifgrant.pdf
git rm crifgrant_insert.tex
git rm crowding/Author_Corrections_ja3112912.rtf
git rm crowding/Emaxluvficoll70_121010_mod.pdf
git rm crowding/Emaxluvficoll70_121010_mod.svg
git rm crowding/cover_letter.htm
git rm crowding/crowding.tex
git rm crowding/crowding_diff.tex
git rm crowding/crowding_summary121023_ed.svg
git rm crowding/email130212.htm
git rm crowding/intpeaksluvficoll70_121010_autoluvficoll70_121010_mod.pdf
git rm crowding/intpeaksluvficoll70_121010_autoluvficoll70_121010_mod.svg
git rm crowding/ksp_corrluvficoll70_121010_mod.pdf
git rm crowding/ksp_corrluvficoll70_121010_mod.svg
git rm crowding/library_abbrev.bib
git rm crowding/mydefs.sty
git rm crowding/myhyperref.sty
git rm crowding/mylatexdiff-preamble.sty
git rm crowding/myparagraphformatting.sty
git rm crowding/reply.tex
git rm crowding/reply_diff.tex
git rm crowding/reply_to_1.tex
git rm crowding/reply_to_1_diff.tex
git rm crowding/reply_to_2.tex
git rm crowding/reply_to_2_diff.tex
git rm crowding/songi_cuts.txt
git rm crowding/songi_email.txt
git rm crowding/songis_second_round.html
git rm crowding/suppinfo.tex
git rm crowding/suppinfo_diff.tex
git rm crowding/t1dataluvficoll70_121010_mod.pdf
git rm crowding/t1dataluvficoll70_121010_mod.svg
git rm crowding/t1luvficoll70_121010_exp23luvficoll70_121010_mod.pdf
git rm crowding/t1luvficoll70_121010_exp23luvficoll70_121010_mod.svg
git rm crowding/toc.png
git rm crowding/toc.svg
git rm crowding/vesicle_compositions.svg
git rm crowding_word_docs/crowding0x.png
git rm crowding_word_docs/crowding1x.png
git rm crowding_word_docs/crowding2x.png
git rm crowding_word_docs/crowding3x.png
git rm crowding_word_docs/crowding4x.png
git rm current_test.py
git rm current_writeup
git rm current_writeup-4_sh.pdf
git rm current_writeup-4_sh.synctex.gz
git rm current_writeup.tex
git rm dannyproc.tex
git rm digatt_instructions.pdf
git rm digatt_instructions.tex
git rm diversity_statement.tex
git rm dna/SI_July11_2013_v1.tex
git rm dna/cmsy10-46.png
git rm dna/cover_letter.htm
git rm dna/dna-diff.tex
git rm dna/dna.html
git rm dna/dna.tex
git rm dna/dna0x.png
git rm dna/dna10x.png
git rm dna/dna11x.png
git rm dna/dna12x.png
git rm dna/dna13x.png
git rm dna/dna14x.png
git rm dna/dna15x.png
git rm dna/dna16x.png
git rm dna/dna17x.png
git rm dna/dna18x.png
git rm dna/dna19x.png
git rm dna/dna1x.png
git rm dna/dna2.html
git rm dna/dna20x.png
git rm dna/dna21x.png
git rm dna/dna22x.png
git rm dna/dna23x.png
git rm dna/dna24x.png
git rm dna/dna25x.png
git rm dna/dna26x.png
git rm dna/dna27x.png
git rm dna/dna28x.png
git rm dna/dna29x.png
git rm dna/dna2x.png
git rm dna/dna3.html
git rm dna/dna30x.png
git rm dna/dna31x.png
git rm dna/dna32x.png
git rm dna/dna33x.png
git rm dna/dna34x.png
git rm dna/dna35x.png
git rm dna/dna3x.png
git rm dna/dna4x.png
git rm dna/dna5x.png
git rm dna/dna6x.png
git rm dna/dna7x.png
git rm dna/dna8x.png
git rm dna/dna9x.png
git rm dna/dna_comments_121022.pdf
git rm dna/dna_figures/1BVD.pdb
git rm dna/dna_figures/1CS2.pdb
git rm dna/dna_figures/1CS2_biotin_R5a_strptvd_complex_parallel_R5a.pdb
git rm dna/dna_figures/1CS2_biotin_R5a_strptvd_complex_vertical_R5a.pdb
git rm dna/dna_figures/3RY2.pdb
git rm dna/dna_figures/SIJuly112013v1-img1.png
git rm dna/dna_figures/SIJuly112013v1-img2.png
git rm dna/dna_figures/SIJuly112013v1-img3.png
git rm dna/dna_figures/SIJuly112013v1-img4.png
git rm dna/dna_figures/comparison_survey.png
git rm dna/dna_figures/comparison_survey.svg
git rm dna/dna_figures/dna_bargraph_120822.pdf
git rm dna/dna_figures/dna_bargraph_120822.png
git rm dna/dna_figures/dna_bargraph_combined.svg
git rm dna/dna_figures/dna_bargraph_klow_120822.pdf
git rm dna/dna_figures/dna_bargraph_klow_120822.png
git rm dna/dna_figures/dna_bargraph_ksigma_120822.pdf
git rm dna/dna_figures/dna_bargraph_ksigma_120822.png
git rm dna/dna_figures/dna_label.jpg
git rm dna/dna_figures/dna_model.pml
git rm dna/dna_figures/dna_model_norender.pml
git rm dna/dna_figures/dna_shortened2_larger.png
git rm dna/dna_figures/dna_streptavidin_w_labels.pdf
git rm dna/dna_figures/dna_streptavidin_w_labels.pdf_tex
git rm dna/dna_figures/dna_streptavidin_w_labels.png
git rm dna/dna_figures/dna_streptavidin_w_labels.svg
git rm dna/dna_figures/final_render.png
git rm dna/dna_figures/final_render_noambient.png
git rm dna/dna_figures/final_render_withmessing.png
git rm dna/dna_figures/final_render_withmessing_ed.png
git rm dna/dna_figures/four_level.pdf
git rm dna/dna_figures/four_level.png
git rm dna/dna_figures/four_level.svg
git rm dna/dna_figures/gel_assay.png
git rm dna/dna_figures/image001.png
git rm dna/dna_figures/interpolation_vs_d_and_D_130730.svg
git rm dna/dna_figures/just_surface.png
git rm dna/dna_figures/ksigma_vs_d_and_D.pdf
git rm dna/dna_figures/ksigma_vs_d_and_D.png
git rm dna/dna_figures/ksigma_vs_d_and_Dchangerot.pdf
git rm dna/dna_figures/ksigma_vs_d_and_Dchangerot.png
git rm dna/dna_figures/ksrat_vs_d_and_Dchangerot.pdf
git rm dna/dna_figures/ksrat_vs_d_and_Dchangerot.png
git rm dna/dna_figures/labelling_scheme.png
git rm dna/dna_figures/labelling_scheme.svg
git rm dna/dna_figures/possible_klow_ksigma_pairs_colord_121014.pdf
git rm dna/dna_figures/possible_klow_ksigma_pairs_colord_121014.png
git rm dna/dna_figures/relaxation_pathways.png
git rm dna/dna_figures/separate_labels.png
git rm dna/dna_figures/spectral_density.pdf
git rm dna/dna_figures/spectral_density.svg
git rm dna/dna_figures/structure_edited.svg
git rm dna/dna_figures/tetramer.png
git rm dna/dna_figures/tetramer.svg
git rm dna/dna_figures/three_tetramers.svg
git rm dna/dna_figures/toc.svg
git rm dna/dna_figures/xi_vs_d_and_D.pdf
git rm dna/dna_figures/xi_vs_d_and_D.png
git rm dna/dna_figures/xi_vs_d_and_Dchangerot.pdf
git rm dna/dna_figures/xi_vs_d_and_Dchangerot.png
git rm dna/dna_new.tex
git rm dna/dna_new0x.png
git rm dna/dna_new10x.png
git rm dna/dna_new11x.png
git rm dna/dna_new13x.png
git rm dna/dna_new14x.png
git rm dna/dna_new15x.png
git rm dna/dna_new16x.png
git rm dna/dna_new17x.png
git rm dna/dna_new1x.png
git rm dna/dna_new2x.png
git rm dna/dna_new3x.png
git rm dna/dna_new4x.png
git rm dna/dna_new5x.png
git rm dna/dna_new6x.png
git rm dna/dna_new7x.png
git rm dna/dna_new8x.png
git rm dna/dna_new9x.png
git rm dna/dna_new_comments.tex
git rm dna/dna_new_diff.tex
git rm dna/dna_new_htmlcomm.html
git rm dna/dna_new_old.tex
git rm dna/dna_version_sent_to_songi.tex
git rm dna/draft_songi_edits.tex
git rm dna/john_140821.txt
git rm dna/library_abbrev.bib
git rm dna/multifrequency.tex
git rm dna/mycolors.sty
git rm dna/mydefs.sty
git rm dna/myhyperref.sty
git rm dna/peter_141007.txt
git rm dna/peter_email130131.tex
git rm dna/peter_email130220.tex
git rm dna/response.tex
git rm dna/songi_email.txt
git rm dna/songi_email_140514.txt
git rm dna/suppinfo.tex
git rm dna/suppinfo_old.tex
git rm dna/table1.csv.tex
git rm dna/table2.csv.tex
git rm dna/table_combined.csv
git rm dna/table_combined.csv.tex
git rm dna/table_combined.csv_forcomp.tex
git rm dna/table_combined.xlsx
git rm dna/test_subcaption.tex
git rm dna_sepcompile/cover_letter.htm
git rm dna_sepcompile/dna_figures/1BVD.pdb
git rm dna_sepcompile/dna_figures/1CS2.pdb
git rm dna_sepcompile/dna_figures/1CS2_biotin_R5a_strptvd_complex_parallel_R5a.pdb
git rm dna_sepcompile/dna_figures/1CS2_biotin_R5a_strptvd_complex_vertical_R5a.pdb
git rm dna_sepcompile/dna_figures/3RY2.pdb
git rm dna_sepcompile/dna_figures/SIJuly112013v1-img3.png
git rm dna_sepcompile/dna_figures/SIJuly112013v1-img4.png
git rm dna_sepcompile/dna_figures/comparison_survey.svg
git rm dna_sepcompile/dna_figures/dna_bargraph_combined.svg
git rm dna_sepcompile/dna_figures/dna_label.jpg
git rm dna_sepcompile/dna_figures/dna_model.pml
git rm dna_sepcompile/dna_figures/dna_model_norender.pml
git rm dna_sepcompile/dna_figures/dna_streptavidin_w_labels.pdf_tex
git rm dna_sepcompile/dna_figures/dna_streptavidin_w_labels.svg
git rm dna_sepcompile/dna_figures/four_level.svg
git rm dna_sepcompile/dna_figures/gel_assay.png
git rm dna_sepcompile/dna_figures/interpolation_vs_d_and_D_130730.svg
git rm dna_sepcompile/dna_figures/labelling_scheme.svg
git rm dna_sepcompile/dna_figures/spectral_density.svg
git rm dna_sepcompile/dna_figures/structure_edited.svg
git rm dna_sepcompile/dna_figures/tetramer.svg
git rm dna_sepcompile/dna_figures/three_tetramers.svg
git rm dna_sepcompile/dna_figures/toc.svg
git rm dna_sepcompile/dna_new.tex
git rm dna_sepcompile/library_abbrev.bib
git rm dna_sepcompile/mydefs.sty
git rm dna_sepcompile/myhyperref.sty
git rm dna_sepcompile/suppinfo.tex
git rm dna_sepcompile/table1.csv.tex
git rm dna_sepcompile/table2.csv.tex
git rm dna_sepcompile/table_combined.csv
git rm dna_sepcompile/table_combined.csv.tex
git rm dna_sepcompile/table_combined.csv_forcomp.tex
git rm dna_sepcompile/table_combined.xlsx
git rm dnp_protocol.tex
git rm dnp_protocol091123.pdf
git rm dnp_protocol091123.tex
git rm edited_master.tex
git rm eip548b.pdf
git rm emails/afosr_141006.txt
git rm emails/for_penny_141012.txt
git rm emails/hardware.svg
git rm emails/hardware_drawing_forgail.svg
git rm emails/nathaniel130812.txt
git rm emails/nikki_practice130715.htm
git rm emails/nlsl_f90_specs.htm
git rm emails/peter130627.txt
git rm emails/presentation_drawing_forgail.svg
git rm emails/probe_only_for_gail.svg
git rm emails/ryans_practice_talk130724.htm
git rm emails/songi_dna_130712.htm
git rm emails/sunyia121012.txt
git rm emails/to_jinsuk_130624.tex
git rm emails/weitzman120924.txt
git rm employee_id.txt
git rm example_notebook.tex
git rm excitation_plot.py
git rm f90_makefile
git rm fanucci_long_visit_2012.xlsx
git rm firefox_popups.txt
git rm folding.vim
git rm for_anna_processing-20111110.csv
git rm for_anna_processing-20111110_1.csv
git rm for_anna_processing.csv
git rm for_george.tex
git rm for_george_ourlab.tex
git rm foraudrey_cpmg.py
git rm foraudrey_summary.tex
git rm foraudrey_t1.py
git rm fordanny.py
git rm forsongi_aminotempoEmax.png
git rm forsongi_aminotempoT1.png
git rm forward_ref2.pdf
git rm forward_ref3.pdf
git rm forward_ref4.pdf
git rm forward_ref5.pdf
git rm forward_refl.pdf
git rm gaussian_shift.py
git rm georges_writeup.docx
git rm gpib_usb.py
git rm groes/.~lock.for_amnon.txt#
git rm "groes/R_1(p)_data_summary140110.png"
git rm "groes/R_1(p)_data_summary140127.png"
git rm groes/R_1_data_T10data140112.pdf
git rm groes/R_1_data_T10data140112.png
git rm "groes/_ksm_R_1(0)_correlation_summary140127.png"
git rm groes/bargraph_summary140127.png
git rm groes/bargraph_summary140127_edited.svg
git rm groes/bargraph_withcorrelation_summary140126.png
git rm groes/comparison_summary140127.png
git rm groes/comparison_summary140127_edited.svg
git rm groes/comparison_survey_120921.pdf
git rm groes/comparison_survey_120921.svg
git rm groes/correlation.svg
git rm groes/data_for_flow.svg
git rm groes/figs_and_captions.htm
git rm groes/flowchart.svg
git rm groes/for_amnon.docx
git rm groes/for_amnon.tex
git rm groes/for_amnon_jf2.docx
git rm groes/for_amnon_jf2_sh_jf.docx
git rm groes/groes_summary_120916.pdf
git rm groes/groes_summary_120916.svg
git rm groes/groes_summary_120921.pdf
git rm groes/groes_summary_120921.svg
git rm groes/hiv_pr_summary_120915.pdf
git rm groes/hiv_pr_summary_xi_120915.pdf
git rm groes/intpeaksgroes_120917_autogroes_120917.pdf
git rm groes/intpeaksgroes_120917_exp23groes_120917.pdf
git rm groes/manual_notes.csv
git rm groes/manual_notes.txt
git rm groes/manual_notes.xlsx
git rm groes/msword/[Content_Types].xml
git rm groes/msword/_rels/.rels
git rm groes/msword/docProps/app.xml
git rm groes/msword/docProps/core.xml
git rm groes/msword/word/_rels/document.xml.rels
git rm groes/msword/word/comments.xml
git rm groes/msword/word/document.xml
git rm groes/msword/word/endnotes.xml
git rm groes/msword/word/fontTable.xml
git rm groes/msword/word/footer1.xml
git rm groes/msword/word/footer2.xml
git rm groes/msword/word/footnotes.xml
git rm groes/msword/word/media/image1.png
git rm groes/msword/word/media/image2.png
git rm groes/msword/word/media/image3.png
git rm groes/msword/word/media/image4.wmf
git rm groes/msword/word/media/image5.wmf
git rm groes/msword/word/media/image6.wmf
git rm groes/msword/word/media/image7.png
git rm groes/msword/word/media/image8.png
git rm groes/msword/word/media/image9.png
git rm groes/msword/word/numbering.xml
git rm groes/msword/word/settings.xml
git rm groes/msword/word/styles.xml
git rm groes/msword/word/theme/theme1.xml
git rm groes/msword/word/webSettings.xml
git rm groes/plan_daniella_songi.tex
git rm groes/pulse_sequence.svg
git rm groes/summary.tex
git rm groes/t1groes_120917_exp23groes_120917.pdf
git rm group_members.txt
git rm gui.py
git rm heating_paper_basic.bbl.bak
git rm hiv_pr/coupling_factor.png
git rm hiv_pr/hiv_pr_summary_120915.pdf
git rm hiv_pr/hiv_pr_summary_120915.svg
git rm hiv_pr/hiv_pr_summary_xi_120915.pdf
git rm hiv_pr/hiv_pr_summary_xi_120915.svg
git rm hiv_pr/relaxivities.png
git rm html_comments.py
git rm html_conversion.tex
git rm html_uncomments.py
git rm htmlcommentsforword.sty
git rm hymn.odt
git rm hymn.txt
git rm index.html
git rm inprocess.tex
git rm inprocess/4ohtseries.tex
git rm inprocess/4ohtseries/adlins.tex
git rm inprocess/4ohtseries/collect_for_adlin.tex
git rm inprocess/4ohtseries/field_series.tex
git rm inprocess/4ohtseries/nice_like_prev.tex
git rm inprocess/4ohtseries/original.tex
git rm inprocess/4ohtseries/probe_compare.tex
git rm inprocess/4ohtseries/repetition.tex
git rm inprocess/4ohtseries/repetition_fresh.tex
git rm inprocess/4ohtseries/statistics.tex
git rm inprocess/95ghz.tex
git rm inprocess/95ghz/initial.tex
git rm inprocess/95ghz/initial/sat_test.tex
git rm inprocess/95ghz/oTP.tex
git rm inprocess/95ghz/temp_test.tex
git rm inprocess/biol_demo.tex
git rm inprocess/biol_demo/adlins.tex
git rm inprocess/biol_demo/initial.tex
git rm inprocess/biol_demo/repeat_tau.tex
git rm inprocess/cocoa.tex
git rm inprocess/compare_100mM.tex
git rm inprocess/conc_xi.tex
git rm inprocess/conc_xi/modelling.tex
git rm inprocess/cpmg.tex
git rm inprocess/cpmg/first.tex
git rm inprocess/cpmg/fourth.tex
git rm inprocess/cpmg/interesting_collect.tex
git rm inprocess/cpmg/plan.tex
git rm inprocess/cpmg/rerun.tex
git rm inprocess/cpmg/third.tex
git rm inprocess/crowding/crowding_dopc.tex
git rm inprocess/crowding/crowding_new.tex
git rm inprocess/crowding/summary121029.tex
git rm inprocess/current_summary.tex
git rm inprocess/dna.tex
git rm inprocess/dna/summary.tex
git rm inprocess/dnp_protocol.tex
git rm inprocess/dnp_protocol_ks.tex
git rm inprocess/fabry_perot.tex
git rm inprocess/fast_k_sigma.tex
git rm inprocess/fitting_test.tex
git rm inprocess/for_cy_data.tex
git rm inprocess/full_diagnostic.tex
git rm inprocess/groes.tex
git rm inprocess/groes/double_ring.tex
git rm inprocess/groes/ficoll.tex
git rm inprocess/groes/first_go.tex
git rm inprocess/groes/groes_diagnose.tex
git rm inprocess/groes/new_label.tex
git rm inprocess/groes/new_label_rerun.tex
git rm inprocess/groes/new_label_rerunt10.tex
git rm inprocess/groes/new_label_summary.tex
git rm inprocess/groes/summary120915.tex
git rm inprocess/groes/summary140110.tex
git rm inprocess/hardware_improvements.tex
git rm inprocess/hardware_improvements.tex~
git rm inprocess/hiv_pr.tex
git rm inprocess/hiv_pr/summary120924.tex
git rm inprocess/jaya_purch_list.tex
git rm inprocess/julia_data.tex
git rm inprocess/lysozyme.tex
git rm inprocess/md.tex
git rm inprocess/md/intro.tex
git rm inprocess/mesh_test.tex
git rm inprocess/microcoil.tex
git rm inprocess/microwave_shaping.tex
git rm inprocess/multiconc.tex
git rm inprocess/rm.tex
git rm inprocess/rm/adlins_data.tex
git rm inprocess/rm/initial_ubq_esr.tex
git rm inprocess/rm/probe.tex
git rm inprocess/rm/summary130508.tex
git rm inprocess/software.tex
git rm inprocess/software/compiled_python.tex
git rm inprocess/software/error_analysis.tex
git rm inprocess/software/plotting.tex
git rm inprocess/stuff_in_progress.tex
git rm inprocess/tdr.tex
git rm inprocess/test_for_ryan.tex
git rm inprocess/thomas.tex
git rm inprocess/unused.tex
git rm inprocess/vesicles_bygeorge.tex
git rm inprocess/vesicles_byme1.tex
git rm inprocess/working_copy.tex
git rm inprocess/writeup_dna.tex
git rm inprocess/writeup_glaser.tex
git rm inprocess/writeup_groes.tex
git rm inprocess/writeup_temperature.tex
git rm inprocess/writeup_temperature/zone_diagram.tex
git rm intro.tex
git rm jcp.bst
git rm jcp_2D_review.tex
git rm jcp_review/3D_view_of_abs_data_DBPh_initial_140507.svg
git rm jcp_review/95GHz_motional_ranges.svg
git rm jcp_review/95_eldor_contours.png
git rm jcp_review/Chiang_FigureREV2.svg
git rm jcp_review/FIGURES-img1.jpg
git rm jcp_review/FIGURES-img11.jpg
git rm jcp_review/FIGURES-img14.jpg
git rm jcp_review/FIGURES-img17.jpg
git rm jcp_review/FIGURES-img18.jpg
git rm jcp_review/FIGURES-img19.jpg
git rm jcp_review/FIGURES-img2.png
git rm jcp_review/FIGURES-img20.png
git rm jcp_review/FIGURES-img21.png
git rm jcp_review/FIGURES-img3.png
git rm jcp_review/FIGURES-img8.png
git rm jcp_review/FIGURES.tex
git rm jcp_review/Fig12.png
git rm jcp_review/Fig_10_MisraFig11_1.jpg
git rm jcp_review/Fig_11_MisraFig11_2b.jpg
git rm jcp_review/Fig_13_EarleFig.png
git rm jcp_review/Fig_13_EarleFig_FP.png
git rm jcp_review/Fig_13_EarleFig_bridge.png
git rm jcp_review/Fig_X_ChiangJCP2011Fig2.png
git rm jcp_review/T2_minimum.png
git rm jcp_review/abstract.docx
git rm jcp_review/block_diagram.png
git rm jcp_review/coherence.svg
git rm jcp_review/convert_figs.sh
git rm jcp_review/create_zip.sh
git rm jcp_review/field_scaling.svg
git rm jcp_review/figure_list.txt
git rm jcp_review/frequency_domain,_Sc__2mMTempo_DBPh_T20ns_512ave_17C_n1p3sw_motional_range_data_150128.png
git rm jcp_review/frequency_domain,_Sc__2mMTempo_DBPh_T20ns_512ave_4p5C_n1p3sw_motional_range_data_150128.png
git rm jcp_review/frequency_domain,_Sc__DMPCTempo_partition_17C_partitioningdata_150128.png
git rm jcp_review/frequency_domain,_Sc__DMPCTempo_partition_37C_partitioningdata_150128.png
git rm jcp_review/frequency_domain,_Sc__tempone_sucrose_5C_motional_range_data_150128.png
git rm jcp_review/jacks_original.tex
git rm jcp_review/jcp2Dreview-img1.pdf
git rm jcp_review/jcp2Dreview-img10.pdf
git rm jcp_review/jcp2Dreview-img11.pdf
git rm jcp_review/jcp2Dreview-img12.pdf
git rm jcp_review/jcp2Dreview-img13.pdf
git rm jcp_review/jcp2Dreview-img14.pdf
git rm jcp_review/jcp2Dreview-img15.pdf
git rm jcp_review/jcp2Dreview-img16.pdf
git rm jcp_review/jcp2Dreview-img17.pdf
git rm jcp_review/jcp2Dreview-img18.pdf
git rm jcp_review/jcp2Dreview-img19.pdf
git rm jcp_review/jcp2Dreview-img2.pdf
git rm jcp_review/jcp2Dreview-img20.pdf
git rm jcp_review/jcp2Dreview-img21.pdf
git rm jcp_review/jcp2Dreview-img22.pdf
git rm jcp_review/jcp2Dreview-img23.pdf
git rm jcp_review/jcp2Dreview-img24.png
git rm jcp_review/jcp2Dreview-img25.pdf
git rm jcp_review/jcp2Dreview-img26.pdf
git rm jcp_review/jcp2Dreview-img27.pdf
git rm jcp_review/jcp2Dreview-img28.pdf
git rm jcp_review/jcp2Dreview-img29.pdf
git rm jcp_review/jcp2Dreview-img3.pdf
git rm jcp_review/jcp2Dreview-img30.pdf
git rm jcp_review/jcp2Dreview-img31.pdf
git rm jcp_review/jcp2Dreview-img32.pdf
git rm jcp_review/jcp2Dreview-img33.pdf
git rm jcp_review/jcp2Dreview-img34.pdf
git rm jcp_review/jcp2Dreview-img35.pdf
git rm jcp_review/jcp2Dreview-img36.pdf
git rm jcp_review/jcp2Dreview-img37.pdf
git rm jcp_review/jcp2Dreview-img38.pdf
git rm jcp_review/jcp2Dreview-img39.pdf
git rm jcp_review/jcp2Dreview-img4.pdf
git rm jcp_review/jcp2Dreview-img40.pdf
git rm jcp_review/jcp2Dreview-img41.pdf
git rm jcp_review/jcp2Dreview-img42.pdf
git rm jcp_review/jcp2Dreview-img43.pdf
git rm jcp_review/jcp2Dreview-img44.pdf
git rm jcp_review/jcp2Dreview-img45.pdf
git rm jcp_review/jcp2Dreview-img46.pdf
git rm jcp_review/jcp2Dreview-img47.pdf
git rm jcp_review/jcp2Dreview-img48.pdf
git rm jcp_review/jcp2Dreview-img49.pdf
git rm jcp_review/jcp2Dreview-img5.pdf
git rm jcp_review/jcp2Dreview-img50.pdf
git rm jcp_review/jcp2Dreview-img51.pdf
git rm jcp_review/jcp2Dreview-img52.pdf
git rm jcp_review/jcp2Dreview-img53.pdf
git rm jcp_review/jcp2Dreview-img54.pdf
git rm jcp_review/jcp2Dreview-img55.pdf
git rm jcp_review/jcp2Dreview-img56.pdf
git rm jcp_review/jcp2Dreview-img57.pdf
git rm jcp_review/jcp2Dreview-img58.pdf
git rm jcp_review/jcp2Dreview-img59.pdf
git rm jcp_review/jcp2Dreview-img6.pdf
git rm jcp_review/jcp2Dreview-img60.pdf
git rm jcp_review/jcp2Dreview-img61.pdf
git rm jcp_review/jcp2Dreview-img62.pdf
git rm jcp_review/jcp2Dreview-img63.pdf
git rm jcp_review/jcp2Dreview-img64.pdf
git rm jcp_review/jcp2Dreview-img7.pdf
git rm jcp_review/jcp2Dreview-img8.pdf
git rm jcp_review/jcp2Dreview-img9.pdf
git rm jcp_review/jcp_2D_review.bbl
git rm jcp_review/jcp_2D_review.tex
git rm jcp_review/jcp_2D_review_nocref.tex
git rm jcp_review/library_abbrev.bib
git rm jcp_review/lipid_partitioning.png
git rm jcp_review/list_of_doi.txt
git rm jcp_review/motional_ranges.png
git rm jcp_review/mycolors.sty
git rm jcp_review/nutation_from_acert_review_2014.svg
git rm jcp_review/partitioning.svg
git rm jcp_review/quasi_bridge.png
git rm jcp_review/scaling_frequency.png
git rm jcp_review/smectic.svg
git rm jeschke_letter.tex
git rm journal_abbrev.txt
git rm julia_adv_mat/bm-2013-000579-revision-request.doc
git rm julia_adv_mat/my_reply.txt
git rm julia_adv_mat/songi_email.txt
git rm kavli.bbl
git rm kavli/2d_grid.png
git rm kavli/2d_grid_2.png
git rm kavli/Jacks_figure.pdf
git rm kavli/Jacks_figure.pdf_tex
git rm kavli/Jacks_figure.svg
git rm kavli/bg_image.png
git rm kavli/bg_image.xcf.gz
git rm kavli/coverletter.tex
git rm kavli/dqc_imaging.pdf
git rm kavli/dqc_imaging.pdf_tex
git rm kavli/dqc_imaging.svg
git rm kavli/kavli.tex
git rm latexdiff
git rm latexscriptNOerr.py
git rm laundry.txt
git rm library_abbrev.bib
git rm lipid_prep091027.xlsx
git rm lipid_prep091102.xlsx
git rm lipidprep100217.xlsx
git rm list_number.txt
git rm lists.tex
git rm lists/ILT_CPMG.tex
git rm lists/artifact.tex
git rm lists/biodemo.tex
git rm lists/cpmg.tex
git rm lists/crowding.tex
git rm lists/delegate.tex
git rm lists/dna.tex
git rm lists/emsley_response.tex
git rm lists/figures/IQ_calibration.jpg
git rm lists/figures/eseem.pdf
git rm lists/figures/eseem_exc_profile.jpg
git rm lists/figures/rd_test.pdf
git rm lists/figures/relative_Qs.jpg
git rm lists/figures/sample_sealing.jpg
git rm lists/figures/server_program.jpg
git rm lists/future_ideas.tex
git rm lists/future_work.tex
git rm lists/general.tex
git rm lists/groes.tex
git rm lists/groes_rem.tex
git rm lists/hfss_95.tex
git rm lists/jack_first_project.tex
git rm lists/jacktalk.tex
git rm lists/jinsuk.tex
git rm lists/lists_old.tex
git rm lists/lowtemp_95.tex
git rm lists/lysozyme.tex
git rm lists/md.tex
git rm lists/microcoil_resonator.tex
git rm lists/mrl.tex
git rm lists/neil.tex
git rm lists/old_posters.tex
git rm lists/others.tex
git rm lists/pope.tex
git rm lists/priorities_old.tex
git rm lists/pulse_shaping.tex
git rm lists/pulse_shaping2.tex
git rm lists/rm.tex
git rm lists/software.tex
git rm lists/software_old.tex
git rm lists/spec_status.tex
git rm lists/sunyia.tex
git rm lists/thomas.tex
git rm lists/trisha_goals_list.tex
git rm lists/unsorted.tex
git rm lists_basic.tex
git rm load_cpmg_emax.py
git rm load_emax.py
git rm load_myh5.py
git rm load_t1_t2_emax.py
git rm mailtopatricia.pdf
git rm mailtopatricia.py
git rm mailtopatricia.tex
git rm matlablike_functions.txt
git rm matrix_demo.ipynb
git rm mc_plots.py
git rm md/first_try.py
git rm md/hydroxytempo.pdb
git rm md/hydroxytempo_ghemical.pdb
git rm md/twod_hydroxy.py
git rm missing_figure.pdf
git rm mma/090730withravi.xls
git rm mma/090805lipidprep.xls
git rm mma/CID_2724321.sdf
git rm mma/CID_2724321.xml
git rm mma/dnp_protocol.aux
git rm mma/dnp_protocol.log
git rm mma/dnp_protocol.pdf
git rm mma/dnp_protocol.tex
git rm mma/dopc.cdx
git rm mma/dopc.svg
git rm mma/dopc_101008_edited.svg
git rm mma/dump_autoplots/esr_forsummary_16dsa.pdf
git rm mma/dump_autoplots/esr_forsummary_16dsa.svg
git rm mma/dump_autoplots/esr_forsummary_doxyl.pdf
git rm mma/dump_autoplots/esr_forsummary_doxyl.svg
git rm mma/dump_autoplots/esr_forsummary_linkers.pdf
git rm mma/dump_autoplots/esr_forsummary_linkers.svg
git rm mma/dump_autoplots/esr_forsummary_longlinkers.pdf
git rm mma/dump_autoplots/esr_forsummary_longlinkers.svg
git rm mma/dump_autoplots/esr_forsummary_tempos.pdf
git rm mma/dump_autoplots/esr_forsummary_tempos.svg
git rm mma/dump_autoplots/octave-core
git rm mma/dump_autoplots/popemca_cr1bylinker.svg
git rm mma/dump_autoplots/popemca_rhobylinker.pdf
git rm mma/dump_autoplots/popemca_taubylinker.pdf
git rm mma/dump_autoplots/popemca_taubylinker.svg
git rm mma/email130212.txt
git rm mma/forarticles.sty
git rm mma/forpresent_esr.svg
git rm mma/fromcy_DOPC_pctempo.xlsx
git rm mma/lipid_prep.xlsx
git rm mma/mmll_and_mmsl.jpg
git rm mma/multivalent.svgz
git rm mma/mynotebookminimal.sty
git rm mma/old_popemca120209_taubylinker_mod.svg
git rm mma/popcg_epr.svgz
git rm mma/pope.cdx
git rm mma/pope.emf
git rm mma/pope.svg
git rm mma/pope_all.svg
git rm mma/pope_all_cleaned.svg
git rm mma/pope_all_reorg.svg
git rm mma/pope_edited.svg
git rm mma/pope_lipid_positions.svg
git rm mma/pope_mca.tex
git rm mma/popeca_100930.pdf
git rm mma/popeca_100930_edited.svg
git rm mma/popem_100930.pdf
git rm mma/popem_100930_edited.svg
git rm mma/popemca13211mod_wlines_sigmabylinker.pdf
git rm mma/preparation.doc
git rm mma/presentation_fusion.png
git rm mma/presentation_fusion.svg
git rm mma/presentation_fusion_dotap.svg
git rm mma/presentation_fusion_horizontal.svg
git rm mma/presentation_fusion_horizontal_ca.svg
git rm mma/presentation_fusion_horizontal_dotap.svg
git rm mma/presentation_fusion_horizontal_dotap1.svg
git rm mma/presentation_fusion_horizontal_dotap2.svg
git rm mma/presentation_fusion_horizontal_dotap3.svg
git rm mma/presentation_fusion_horizontal_dotap4.svg
git rm mma/presentation_fusion_horizontal_m.svg
git rm mma/presentation_fusion_horizontal_mx.svg
git rm mma/presentation_fusion_horizontal_popc.svg
git rm mma/presentation_fusion_horizontal_reaction.svg
git rm mma/presentation_fusion_horizontal_readyforsingle.svg
git rm mma/presentation_fusion_justm.svg
git rm mma/presentation_fusion_nomx.svg
git rm mma/presentation_fusion_popc.svg
git rm mma/revtex_wrapper.tex
git rm mma/summary.tex
git rm mma/withpopc.svgz
git rm mompass.txt
git rm montecarlofunctions.py
git rm mylatexdiff-preamble.sty
git rm mystreamplot.py
git rm mystyle.bst
git rm nandini_cv_2010.tex
git rm nandini_cv_compile.sh
git rm nando/DSC00312.JPG
git rm nando/logo.png
git rm nando/request_for_evidence.tex
git rm nando/sign1.png
git rm nando/traced_animals.svg
git rm nando/traced_animals_straightened.svg
git rm naveed090909.xlsx
git rm new_hydroxytempo_plot.py
git rm new_probe_pieces.jpg
git rm new_probe_pieces.xcf.gz
git rm newmcfuncs.py
git rm nih_update/Three_line_summary_120320_tk_jf.docx
git rm nih_update/block_diagram.png
git rm nih_update/cancellation_result.pdf
git rm nih_update/cancellation_result.png
git rm nih_update/cancellation_result.svgz
git rm nih_update/myconfig.cfg
git rm nih_update/nih_update.tex
git rm nih_update/time_sequence.png
git rm nih_update/time_sequence.svgz
git rm nlshlp_formatted.txt
git rm notebook091102.tex
git rm notebook091109.tex
git rm notebook091116.tex
git rm notebook091217.tex
git rm notebook100105.tex
git rm notebook100120.tex
git rm notebook100202.tex
git rm notebook100301.tex
git rm notebook100312.tex
git rm notebook100324.tex
git rm notebook100402.tex
git rm notebook100414.tex
git rm notebook100426.tex
git rm notebook100503.tex
git rm notebook100524.tex
git rm notebook100601.tex
git rm notebook100702.tex
git rm notebook100811.tex
git rm notebook100901.tex
git rm notebook101001.tex
git rm notebook101101.tex
git rm notebook101130.tex
git rm notebook101213.tex
git rm notebook110101.tex
git rm notebook110304.tex
git rm notebook110407.tex
git rm notebook110528.tex
git rm notebook110601.tex
git rm notebook111101.tex
git rm notebook120103.tex
git rm notebook120221.tex
git rm notebook120502.tex
git rm notebook120724.tex
git rm notebook120924.tex
git rm notebook121112.tex
git rm notebook130101.tex
git rm notebook130305.tex
git rm notebook130511.tex
git rm notebook130701.tex
git rm notebook131009.tex
git rm notebook140102.tex
git rm notebook140203.tex
git rm notebook140304.tex
git rm notebook140401.tex
git rm notebook140512.tex
git rm notebook140627.tex
git rm notebook140804.tex
git rm notebook141027.tex
git rm notebook150127.tex
git rm numbers6.txt
git rm old_figures/msd_johnout.png
git rm old_figures/msd_traj.png
git rm old_figures/msd_trajout.png
git rm old_figures/reftovna.png
git rm old_figures/vna1.pdf
git rm old_figures/vna2.pdf
git rm old_proc.py
git rm onewordify.py
git rm onewordify_undo.py
git rm opt_target_bounded.py
git rm papers.tex
git rm past_research_basic.bbl
git rm past_research_basic.tex
git rm pastedpic_10222009_110634.png
git rm pdf_tools/bookprint
git rm pdf_tools/cat.sh
git rm pdf_tools/convert_eps.sh
git rm pdf_tools/convert_eps_all.sh
git rm pdf_tools/curves.sh
git rm pdf_tools/embed.sh
git rm pdf_tools/fromsunyia.csv
git rm pdf_tools/latexdiff-so
git rm pdf_tools/make1word.sh
git rm pdf_tools/match_spacing.sh
git rm pdf_tools/mathml
git rm pdf_tools/printtousb
git rm pdf_tools/ps2book
git rm pdf_tools/remove.sh
git rm pdf_tools/un1word.sh
git rm plot_foradlin.py
git rm pnmrs.bst
git rm povray/Si_sample.pov
git rm povray/Si_sample_etched.pov
git rm povray/Si_sample_nomask.pov
git rm povray/Si_scene.inc
git rm povray/aberatn.ttf
git rm povray/all_uses-1.pov
git rm povray/all_uses-2.pov
git rm povray/all_uses-3.pov
git rm povray/all_uses.pov
git rm povray/animate.sh
git rm povray/animate_test.sh
git rm povray/chemical.pov
git rm povray/conical.pov
git rm povray/darpa/addition.pov
git rm povray/darpa/addition_sph.pov
git rm povray/darpa/common
git rm povray/darpa/multi_coil.pov
git rm povray/darpa/multi_coil_sph.pov
git rm povray/darpa/myheader.inc
git rm povray/darpa/povray.txt
git rm povray/darpa/test
git rm povray/demo.pov
git rm povray/encexamples/surface1.pov
git rm povray/encexamples/surface1_pov.inc
git rm povray/encexamples/surface1_pov.ini
git rm povray/encexamples/surface1_pov_mat.inc
git rm povray/encexamples/surface2.pov
git rm povray/encexamples/surface2_pov.inc
git rm povray/encexamples/surface2_pov.ini
git rm povray/encexamples/surface2_pov_mat.inc
git rm povray/encexamples/surface3.pov
git rm povray/encexamples/surface3_pov.inc
git rm povray/encexamples/surface3_pov.ini
git rm povray/encexamples/surface3_pov_mat.inc
git rm povray/encexamples/surface4.pov
git rm povray/encexamples/surface4_pov.inc
git rm povray/encexamples/surface4_pov.ini
git rm povray/encexamples/surface4_pov_mat.inc
git rm povray/ex_situ_fixed.pov
git rm povray/ex_situ_nomag.pov
git rm povray/ex_situ_nosum.pov
git rm povray/example.pov
git rm povray/geology.pov
git rm povray/insidemagnet.pov
git rm povray/largesample.pov
git rm povray/magnet.pov
git rm povray/magnet_anim.pov
git rm povray/magnet_clear.pov
git rm povray/magnet_fly.pov
git rm povray/magnet_none.pov
git rm povray/medical_down.pov
git rm povray/medical_up.pov
git rm povray/mothersday.pov
git rm povray/mri/mri.ini
git rm povray/mri/mri.pov
git rm povray/my.ini
git rm povray/myheader.inc
git rm povray/newsolenoid.pov
git rm povray/newtest.pov
git rm povray/notsquare.sh
git rm povray/oldmyheader.inc
git rm povray/oldnmr.pov
git rm povray/oldnmr_solid.pov
git rm povray/phantom.pov
git rm povray/phantom_empty.pov
git rm povray/phantom_sol.pov
git rm povray/povray.txt
git rm povray/probe.pov
git rm povray/probe2.pov
git rm povray/room_example.pov
git rm povray/rot_mag.pov
git rm povray/rotor.pov
git rm povray/shimpulse.pov
git rm povray/solenoid.pov
git rm povray/stretched.sh
git rm povray/template.pov
git rm povray/test.pov
git rm povray/test.sh
git rm povray/text.pov
git rm povray/theprobe_forpovray.pov
git rm povray/theprobe_forpovray_inside.pov
git rm povray/theprobe_forpovray_inside_pov.inc
git rm povray/theprobe_forpovray_inside_pov.ini
git rm povray/theprobe_forpovray_inside_pov_mat.inc
git rm povray/theprobe_forpovray_pov.inc
git rm povray/theprobe_forpovray_pov.ini
git rm povray/theprobe_forpovray_pov_mat.inc
git rm power_law_fit.py
git rm pp_progs/mac/jf_zg
git rm pp_progs/pp/jf_fir
git rm pp_progs/pp/jf_fir_ph
git rm pp_progs/pp/jf_nut
git rm pp_progs/pp/jf_satrec
git rm pp_progs/pp/jf_satrec_ph
git rm pp_progs/pp/jf_zg_ph
git rm pp_progs/pp/zg
git rm pp_progs/vd/jf_sat_forsigma
git rm pp_progs/vd/jf_sat_wat
git rm pp_progs/vd/johnsatrec
git rm pp_progs/vd/johnsatrec_long
git rm pp_progs/vd/johnsatrec_longer
git rm progress.pdf
git rm prop_figures/awg_schematic.svgz
git rm prop_figures/fuel_cell.pdf
git rm prop_figures/fuel_cell.svgz
git rm prop_figures/kruer.pdf
git rm prop_figures/kruer.png
git rm prop_figures/kruer.svgz
git rm prop_figures/kruer_path.svg
git rm prop_figures/nafion.png
git rm prop_figures/nmr_pulse.svgz
git rm prop_figures/pulse_sequence.pdf
git rm prop_figures/pulse_sequence.svgz
git rm propagator.so
git rm proposal/Colorado/abstract.txt
git rm proposal/README.txt
git rm proposal/alex_email_1409014.txt
git rm proposal/alex_letter_140926.tex
git rm proposal/alpha_beta_schematic.svg
git rm proposal/article_wrapper.tex
git rm proposal/bu.tex
git rm proposal/capital_equipment_RI.tex
git rm proposal/conf.txt
git rm proposal/cover_letter.tex
git rm proposal/cover_letter_Alberta.tex
git rm proposal/cover_letter_Binghamton.tex
git rm proposal/cover_letter_BostC.tex
git rm proposal/cover_letter_Buffalo.tex
git rm proposal/cover_letter_CUNY.tex
git rm proposal/cover_letter_Colorado.tex
git rm proposal/cover_letter_Cornell.tex
git rm proposal/cover_letter_CornellPhys.tex
git rm proposal/cover_letter_Denver.tex
git rm proposal/cover_letter_Denver_refonly.tex
git rm proposal/cover_letter_GeorgiaTech.tex
git rm proposal/cover_letter_Illinois.tex
git rm proposal/cover_letter_Kent.tex
git rm proposal/cover_letter_Knoxville.tex
git rm proposal/cover_letter_Maryland.tex
git rm proposal/cover_letter_Maryland_refonly.tex
git rm proposal/cover_letter_NDSU.tex
git rm proposal/cover_letter_NYU.tex
git rm proposal/cover_letter_Oregon.tex
git rm proposal/cover_letter_PennState.tex
git rm proposal/cover_letter_Princeton.tex
git rm proposal/cover_letter_Riverside.tex
git rm proposal/cover_letter_Stanford.tex
git rm proposal/cover_letter_TexAM.tex
git rm proposal/cover_letter_UBC.tex
git rm proposal/cover_letter_UCSC.tex
git rm proposal/cover_letter_UChicago.tex
git rm proposal/cover_letter_UIC.tex
git rm proposal/cover_letter_UMN.tex
git rm proposal/cover_letter_UMN_refonly.tex
git rm proposal/cover_letter_UMich.tex
git rm proposal/cover_letter_UTEP.tex
git rm proposal/cover_letter_UTEP_refonly.tex
git rm proposal/cover_letter_VCU.tex
git rm proposal/cover_letter_Washington.tex
git rm proposal/diversity.tex
git rm proposal/email_to_alex_accomplishments_101011.htm
git rm proposal/equipment_CUNY.tex
git rm proposal/equipment_VCU.tex
git rm proposal/figs_from_refs/Hara2013_5.jpg
git rm proposal/figs_from_refs/Hara2013_combined.svg
git rm proposal/figs_from_refs/Hara2013_toc.jpg
git rm proposal/figs_from_refs/Signal_transduction_pathways.svg
git rm proposal/figs_from_refs/Spiegel2014_1a.jpg
git rm proposal/figs_from_refs/fechete2009.svg
git rm proposal/figs_from_refs/fechete2009_8a.jpg
git rm proposal/figs_from_refs/fechete2009_toc.jpg
git rm proposal/figs_from_refs/fechete2009_vertical.svg
git rm proposal/from_2011.tex
git rm proposal/graphical_abstract.pdf
git rm proposal/graphical_abstract.svg
git rm proposal/hycolor.sty
git rm proposal/library.bib
git rm proposal/logo.png
git rm proposal/makefile
git rm proposal/minnesota.tex
git rm proposal/mynotebook.sty
git rm proposal/mynotebookminimal.sty
git rm proposal/newjoblist.txt
git rm proposal/past_research.tex
git rm proposal/pdfcomment.sty
git rm proposal/positions.xlsx
git rm proposal/positions_distribute.xlsx
git rm proposal/positions_fordaniele.xlsx
git rm proposal/positions_forjack.xlsx
git rm proposal/prop_for_alex.tex
git rm proposal/proposal.tex
git rm proposal/reference_contactinfo.txt
git rm proposal/signature.svg
git rm proposal/solid_state.tex
git rm proposal/summary_from_email.odt
git rm proposal/summary_from_email.txt
git rm proposal/teaching.tex
git rm proposal/temp.tex
git rm proposal/umichinfo.txt
git rm proposal/xcolor-patch.sty
git rm proposal_basic.tex
git rm prospa.py
git rm protocols/"Letter to John 280512 the experiment protocol.docx"
git rm protocols/dnp_minimal.tex
git rm publication_list.tex
git rm pulse_esr_list.tex
git rm py_fromslb/different_rotations.py
git rm py_fromslb/ft.py
git rm py_fromslb/ft_comp.py
git rm py_fromslb/isf_dpo.py
git rm py_fromslb/matlablike.py,v
git rm py_fromslb/matlablike.py.backupmistake
git rm py_fromslb/plot_echoes.py
git rm py_fromslb/plotwaves.py
git rm py_fromslb/preamped.py
git rm py_fromslb/preamped_avg.py
git rm py_fromslb/process_echoes.py
git rm py_fromslb/runcomp.py
git rm py_fromslb/span_selector.py
git rm py_fromslb/specgram_wsel.py
git rm py_fromslb/stack_pulses.py
git rm py_fromslb/testplot2.py
git rm py_fromslb/testwaves.py
git rm pylab_workaround.py
git rm quant_odnp/Aug2quant_odnp_sh.pdf
git rm quant_odnp/Songi-edited.bbl
git rm quant_odnp/Songi-edited.pdf
git rm quant_odnp/Songi-edited.synctex.gz
git rm quant_odnp/Songi-edited.tex
git rm quant_odnp/abstract.tex
git rm quant_odnp/figures/2,2,6,6-Tetramethylpiperidinyloxyl.svg
git rm quant_odnp/figures/Emax.jpg
git rm quant_odnp/figures/Emax.pdf
git rm quant_odnp/figures/Emax.png
git rm quant_odnp/figures/Emax.svg
git rm quant_odnp/figures/Emaxhydroxytempo_100mM_100916.jpg
git rm quant_odnp/figures/Emaxhydroxytempo_100mM_100916.pdf
git rm quant_odnp/figures/Emaxhydroxytempo_100mM_100916.png
git rm quant_odnp/figures/Emaxhydroxytempo_1250uM_101006.jpg
git rm quant_odnp/figures/Emaxhydroxytempo_1250uM_101006.pdf
git rm quant_odnp/figures/Emaxhydroxytempo_1250uM_101006.png
git rm quant_odnp/figures/Emaxhydroxytempo_150uM_100923.jpg
git rm quant_odnp/figures/Emaxhydroxytempo_150uM_100923.pdf
git rm quant_odnp/figures/Emaxhydroxytempo_150uM_100923.png
git rm quant_odnp/figures/Eviphydroxytempo_100mM_100916.jpg
git rm quant_odnp/figures/Eviphydroxytempo_100mM_100916.pdf
git rm quant_odnp/figures/Eviphydroxytempo_100mM_100916.png
git rm quant_odnp/figures/Eviphydroxytempo_150uM_100923.jpg
git rm quant_odnp/figures/Eviphydroxytempo_150uM_100923.pdf
git rm quant_odnp/figures/Eviphydroxytempo_150uM_100923.png
git rm quant_odnp/figures/adlin_email_withunc_130404.svg
git rm quant_odnp/figures/blur_image.png
git rm quant_odnp/figures/blur_image.xcf.gz
git rm quant_odnp/figures/comparison_survey.png
git rm quant_odnp/figures/comparison_survey.svgz
git rm quant_odnp/figures/composite_Emax_Evip.jpg
git rm quant_odnp/figures/composite_Emax_Evip.pdf
git rm quant_odnp/figures/composite_Emax_Evip.png
git rm quant_odnp/figures/composite_Emax_Evip.svg
git rm quant_odnp/figures/convert.sh
git rm quant_odnp/figures/dopc.pdf
git rm quant_odnp/figures/dopc.png
git rm quant_odnp/figures/dopc.svgz
git rm quant_odnp/figures/fcr_vs_dnp.pdf
git rm quant_odnp/figures/fcr_vs_dnp.png
git rm quant_odnp/figures/fcr_vs_dnp.svg
git rm quant_odnp/figures/graphical_outline.png
git rm quant_odnp/figures/graphical_outline.svg
git rm quant_odnp/figures/hindman.jpg
git rm quant_odnp/figures/hindman.pdf
git rm quant_odnp/figures/hindman.png
git rm quant_odnp/figures/hindman.svgz
git rm quant_odnp/figures/hydroxytempo.cdx
git rm quant_odnp/figures/hydroxytempo.jpg
git rm quant_odnp/figures/hydroxytempo.pdf
git rm quant_odnp/figures/hydroxytempo.png
git rm quant_odnp/figures/ksmax.pdf
git rm quant_odnp/figures/ksmax.png
git rm quant_odnp/figures/ksmax.svgz
git rm quant_odnp/figures/multifitxismaxhydroxytempo_100mM_100916.jpg
git rm quant_odnp/figures/multifitxismaxhydroxytempo_100mM_100916.pdf
git rm quant_odnp/figures/multifitxismaxhydroxytempo_100mM_100916.png
git rm quant_odnp/figures/multifitxismaxhydroxytempo_1250uM_101006.jpg
git rm quant_odnp/figures/multifitxismaxhydroxytempo_1250uM_101006.pdf
git rm quant_odnp/figures/multifitxismaxhydroxytempo_1250uM_101006.png
git rm quant_odnp/figures/multifitxismaxhydroxytempo_150uM_100923.jpg
git rm quant_odnp/figures/multifitxismaxhydroxytempo_150uM_100923.pdf
git rm quant_odnp/figures/multifitxismaxhydroxytempo_150uM_100923.png
git rm quant_odnp/figures/multifitxismaxpopcg_4mM_5p_mmll_110510.jpg
git rm quant_odnp/figures/multifitxismaxpopcg_4mM_5p_mmll_110510.pdf
git rm quant_odnp/figures/multifitxismaxpopcg_4mM_5p_mmll_110510.png
git rm quant_odnp/figures/multifitxismaxpopcg_4mM_5p_mmll_110510.svgz
git rm quant_odnp/figures/new_comparison_less0.jpg
git rm quant_odnp/figures/new_comparison_less0.pdf
git rm quant_odnp/figures/new_comparison_less0.png
git rm quant_odnp/figures/new_comparison_less0.svgz
git rm quant_odnp/figures/new_hydroxytempo_plot_xi_option_130222.pdf
git rm quant_odnp/figures/new_hydroxytempo_plot_xi_option_130222.png
git rm quant_odnp/figures/newlinearhydroxytempo_150uM_100923.jpg
git rm quant_odnp/figures/newlinearhydroxytempo_150uM_100923.pdf
git rm quant_odnp/figures/newlinearhydroxytempo_150uM_100923.png
git rm quant_odnp/figures/oleinikova.png
git rm quant_odnp/figures/planned_mods.jpg
git rm quant_odnp/figures/planned_mods_small.jpg
git rm quant_odnp/figures/rel_plots/Emaxhydroxytempo_100mM_14scfh_130211.pdf
git rm quant_odnp/figures/rel_plots/Emaxhydroxytempo_1250uM_120120.pdf
git rm quant_odnp/figures/rel_plots/ksp_corrhydroxytempo_100mM_100916.pdf
git rm quant_odnp/figures/rel_plots/ksp_corrhydroxytempo_100mM_14scfh_130211.pdf
git rm quant_odnp/figures/rel_plots/ksp_corrhydroxytempo_1250uM_120120.pdf
git rm quant_odnp/figures/rel_plots/ksp_corrhydroxytempo_150uM_120120.pdf
git rm quant_odnp/figures/rel_plots/t10datahydroxytempo_100mM_100916.pdf
git rm quant_odnp/figures/rel_plots/t10datahydroxytempo_10uM_120123.pdf
git rm quant_odnp/figures/rel_plots/t10datahydroxytempo_1250uM_120120.pdf
git rm quant_odnp/figures/rel_plots/t10datahydroxytempo_150uM_120120.pdf
git rm quant_odnp/figures/rel_plots/t10datatest110307.pdf
git rm quant_odnp/figures/rel_plots/t10datatest110307.svg
git rm quant_odnp/figures/rel_plots/t1datahydroxytempo_100mM_14scfh_130211.pdf
git rm quant_odnp/figures/t10datahydroxytempo_100mM_100916.jpg
git rm quant_odnp/figures/t10datahydroxytempo_100mM_100916.pdf
git rm quant_odnp/figures/t10datahydroxytempo_100mM_100916.png
git rm quant_odnp/figures/t10datahydroxytempo_100mM_100916.svgz
git rm quant_odnp/figures/t10datahydroxytempo_1250uM_101006.jpg
git rm quant_odnp/figures/t10datahydroxytempo_1250uM_101006.pdf
git rm quant_odnp/figures/t10datahydroxytempo_1250uM_101006.png
git rm quant_odnp/figures/t10datahydroxytempo_1250uM_101006.svgz
git rm quant_odnp/figures/t10datahydroxytempo_150uM_100923.jpg
git rm quant_odnp/figures/t10datahydroxytempo_150uM_100923.pdf
git rm quant_odnp/figures/t10datahydroxytempo_150uM_100923.png
git rm quant_odnp/figures/t10datahydroxytempo_150uM_100923.svgz
git rm quant_odnp/figures/t10datapopcg_4mM_5p_mmll_110510.jpg
git rm quant_odnp/figures/t10datapopcg_4mM_5p_mmll_110510.pdf
git rm quant_odnp/figures/t10datapopcg_4mM_5p_mmll_110510.png
git rm quant_odnp/figures/t10datapopcg_4mM_5p_mmll_110510.svgz
git rm quant_odnp/figures/t10datatest110307.jpg
git rm quant_odnp/figures/t10datatest110307.pdf
git rm quant_odnp/figures/t10datatest110307.png
git rm quant_odnp/figures/t10datatest110307.svg
git rm quant_odnp/figures/t1_vs_temp.jpg
git rm quant_odnp/figures/t1_vs_temp.pdf
git rm quant_odnp/figures/t1_vs_temp.png
git rm quant_odnp/figures/t1_vs_temp.svg
git rm quant_odnp/figures/t1vsp.pdf
git rm quant_odnp/figures/t1vsp.png
git rm quant_odnp/figures/t1vsp.svg
git rm quant_odnp/figures/toc.svg
git rm quant_odnp/figures/xismax.jpg
git rm quant_odnp/figures/xismax.pdf
git rm quant_odnp/figures/xismax.png
git rm quant_odnp/figures/xismax.svgz
git rm quant_odnp/figures/xismax_vs_C_120314.pdf
git rm quant_odnp/figures/xismax_vs_C_120314.png
git rm quant_odnp/figures/xismax_vs_C_120314.svg
git rm quant_odnp/h-elsevier.bst
git rm quant_odnp/highlights.txt
git rm quant_odnp/journal_abbrev.txt
git rm quant_odnp/library.bib
git rm quant_odnp/mynotes.bib
git rm quant_odnp/pnmrs.bst
git rm quant_odnp/pnmrs_nando.bst
git rm quant_odnp/quant_odnp.css
git rm quant_odnp/quant_odnp.tex
git rm quant_odnp/quant_odnp.tex.old
git rm quant_odnp/quant_odnp0x.png
git rm quant_odnp/quant_odnp100x.png
git rm quant_odnp/quant_odnp101x.png
git rm quant_odnp/quant_odnp102x.png
git rm quant_odnp/quant_odnp103x.png
git rm quant_odnp/quant_odnp104x.png
git rm quant_odnp/quant_odnp105x.png
git rm quant_odnp/quant_odnp106x.png
git rm quant_odnp/quant_odnp10x.png
git rm quant_odnp/quant_odnp11x.png
git rm quant_odnp/quant_odnp12x.png
git rm quant_odnp/quant_odnp13x.png
git rm quant_odnp/quant_odnp14x.png
git rm quant_odnp/quant_odnp15x.png
git rm quant_odnp/quant_odnp16x.png
git rm quant_odnp/quant_odnp17x.png
git rm quant_odnp/quant_odnp18x.png
git rm quant_odnp/quant_odnp19x.png
git rm quant_odnp/quant_odnp1x.png
git rm quant_odnp/quant_odnp2.html
git rm quant_odnp/quant_odnp20x.png
git rm quant_odnp/quant_odnp21x.png
git rm quant_odnp/quant_odnp22x.png
git rm quant_odnp/quant_odnp23x.png
git rm quant_odnp/quant_odnp24x.png
git rm quant_odnp/quant_odnp25x.png
git rm quant_odnp/quant_odnp26x.png
git rm quant_odnp/quant_odnp27x.png
git rm quant_odnp/quant_odnp28x.png
git rm quant_odnp/quant_odnp29x.png
git rm quant_odnp/quant_odnp2x.png
git rm quant_odnp/quant_odnp30x.png
git rm quant_odnp/quant_odnp31x.png
git rm quant_odnp/quant_odnp32x.png
git rm quant_odnp/quant_odnp33x.png
git rm quant_odnp/quant_odnp34x.png
git rm quant_odnp/quant_odnp35x.png
git rm quant_odnp/quant_odnp36x.png
git rm quant_odnp/quant_odnp37x.png
git rm quant_odnp/quant_odnp38x.png
git rm quant_odnp/quant_odnp39x.png
git rm quant_odnp/quant_odnp3x.png
git rm quant_odnp/quant_odnp40x.png
git rm quant_odnp/quant_odnp41x.png
git rm quant_odnp/quant_odnp42x.png
git rm quant_odnp/quant_odnp43x.png
git rm quant_odnp/quant_odnp44x.png
git rm quant_odnp/quant_odnp45x.png
git rm quant_odnp/quant_odnp46x.png
git rm quant_odnp/quant_odnp47x.png
git rm quant_odnp/quant_odnp48x.png
git rm quant_odnp/quant_odnp49x.png
git rm quant_odnp/quant_odnp4x.png
git rm quant_odnp/quant_odnp50x.png
git rm quant_odnp/quant_odnp51x.png
git rm quant_odnp/quant_odnp52x.png
git rm quant_odnp/quant_odnp53x.png
git rm quant_odnp/quant_odnp54x.png
git rm quant_odnp/quant_odnp55x.png
git rm quant_odnp/quant_odnp56x.png
git rm quant_odnp/quant_odnp57x.png
git rm quant_odnp/quant_odnp58x.png
git rm quant_odnp/quant_odnp59x.png
git rm quant_odnp/quant_odnp5x.png
git rm quant_odnp/quant_odnp60x.png
git rm quant_odnp/quant_odnp61x.png
git rm quant_odnp/quant_odnp62x.png
git rm quant_odnp/quant_odnp63x.png
git rm quant_odnp/quant_odnp64x.png
git rm quant_odnp/quant_odnp65x.png
git rm quant_odnp/quant_odnp66x.png
git rm quant_odnp/quant_odnp67x.png
git rm quant_odnp/quant_odnp68x.png
git rm quant_odnp/quant_odnp69x.png
git rm quant_odnp/quant_odnp6x.png
git rm quant_odnp/quant_odnp70x.png
git rm quant_odnp/quant_odnp71x.png
git rm quant_odnp/quant_odnp72x.png
git rm quant_odnp/quant_odnp73x.png
git rm quant_odnp/quant_odnp74x.png
git rm quant_odnp/quant_odnp75x.png
git rm quant_odnp/quant_odnp76x.png
git rm quant_odnp/quant_odnp77x.png
git rm quant_odnp/quant_odnp78x.png
git rm quant_odnp/quant_odnp79x.png
git rm quant_odnp/quant_odnp7x.png
git rm quant_odnp/quant_odnp80x.png
git rm quant_odnp/quant_odnp81x.png
git rm quant_odnp/quant_odnp82x.png
git rm quant_odnp/quant_odnp83x.png
git rm quant_odnp/quant_odnp84x.png
git rm quant_odnp/quant_odnp85x.png
git rm quant_odnp/quant_odnp86x.png
git rm quant_odnp/quant_odnp87x.png
git rm quant_odnp/quant_odnp88x.png
git rm quant_odnp/quant_odnp89x.png
git rm quant_odnp/quant_odnp8x.png
git rm quant_odnp/quant_odnp90x.png
git rm quant_odnp/quant_odnp91x.png
git rm quant_odnp/quant_odnp92x.png
git rm quant_odnp/quant_odnp93x.png
git rm quant_odnp/quant_odnp94x.png
git rm quant_odnp/quant_odnp95x.png
git rm quant_odnp/quant_odnp96x.png
git rm quant_odnp/quant_odnp97x.png
git rm quant_odnp/quant_odnp98x.png
git rm quant_odnp/quant_odnp99x.png
git rm quant_odnp/quant_odnp9x.png
git rm quant_odnp/quant_odnpNotes.bib
git rm quant_odnp/quant_odnp_dspace_sh.pdf
git rm quant_odnp/quant_odnp_dspace_sh.synctex.gz
git rm quant_odnp/quant_odnp_htmlcomm.html
git rm quant_odnp/quant_odnp_shfirsthalf.tex
git rm quant_odnp/response.tex
git rm quant_odnp/response_sh.pdf
git rm quant_odnp/review.docx
git rm quant_odnp/widetext.sty
git rm receiver25dB_test.pdf
git rm receiver25dB_test_fid.pdf
git rm receiver_test25dB.pdf
git rm receiver_test25dB_bad.pdf
git rm receiver_test25dBfid.pdf
git rm receiver_test25dBfid_bad.pdf
git rm reception_tickets.txt
git rm relaxivity_functions.py
git rm remove_empty.sh
git rm repeat_make_opt.sh
git rm res.cls
git rm reviews/article_wrapper.tex
git rm reviews/bennati_sat.tex
git rm reviews/library.bib
git rm reviews/makefile
git rm reviews/mynotebook.sty
git rm revtex_wrapper.tex
git rm rho_plot.py
git rm rm/correlation.svg
git rm rm/draft.tex
git rm rm/epr_combinedesr_130827.svg
git rm rm/ksigma_correlation_ubiquitin_summary130827.pdf
git rm rm/ksigma_correlation_ubiquitin_summary130827.png
git rm rm/ksigma_correlation_ubiquitin_summary130827.svg
git rm rm/processing_figure/Emaxubq_Q49_15N_2_130714.svg
git rm rm/processing_figure/ksp_corrubq_Q49_15N_2_130714.svg
git rm rm/processing_figure/t1dataubq_Q49_15N_2_130714.svg
git rm rm/rm_esr_summary_from_stuff_while_nathaniel_was_here.png
git rm rm/ubiquitin/1G6J.pdb
git rm rm/ubiquitin/residue_summary.svg
git rm rm/ubiquitin/ubiquitin_back.png
git rm rm/ubiquitin/ubiquitin_basic.pml
git rm rm/ubiquitin/ubiquitin_front.png
git rm rm/ubiquitin/ubiquitin_norender.pml
git rm rm/ubiquitin/wand_view1.png
git rm rm/ubiquitin/wand_view2.png
git rm rm/ubiquitin/wand_view3.png
git rm rmc_T2_plot.py
git rm rmc_waveform_plot.py
git rm run_tex.bat
git rm runtest.py
git rm saturation.nb
git rm saturation1.pdf
git rm save_info.txt
git rm save_registers.txt
git rm scan1_100305.jpg
git rm scan1_100305.png
git rm scan2_100305.jpg
git rm separate_comments.py
git rm sezer_math_141113.ipynb
git rm sketches/3D_view_of_abs_data_DBPh_initial_140507.svg
git rm sketches/3line_forsat.jpg
git rm sketches/95GHz_motional_ranges.svg
git rm sketches/CNF_notes.jpg
git rm sketches/Hardware_status.svgz
git rm sketches/"Picture 11.jpg"
git rm sketches/"Picture 11.png"
git rm sketches/ampwjerry.jpg
git rm sketches/animatepdb.py
git rm sketches/audrey_dialcpmgexpl_before100629.png
git rm sketches/audrey_dialexpl_before100629.png
git rm sketches/audrey_listtodo_before100629.png
git rm sketches/audrey_meeting2_100629.png
git rm sketches/audrey_meeting_100629.png
git rm sketches/audrey_meeting_suppl_100629.png
git rm sketches/audrey_pmworkflow100701.jpg
git rm sketches/audrey_pythonexpl_before100629.png
git rm sketches/ballandstick.pml
git rm sketches/code_expl.png
git rm sketches/code_expl.xcf.gz
git rm sketches/code_expl_nonobj.png
git rm sketches/code_expl_obj.png
git rm sketches/coding_expl_difffuncs.svgz
git rm sketches/coding_expl_inheritance.png
git rm sketches/colorwheel.pdf
git rm sketches/colorwheel.png
git rm sketches/dpph.png
git rm sketches/forkeith.svg
git rm sketches/forkeith_lipc.svg
git rm sketches/grid.svgz
git rm sketches/hatch.svgz
git rm sketches/hydroxytempo.gpr
git rm sketches/hydroxytempo.jpg
git rm sketches/hydroxytempo.pdb
git rm sketches/hydroxytempo.pml
git rm sketches/hydroxytempo_distances.txt
git rm sketches/inkscape_pasted_image_20110524_201049.png
git rm sketches/inkscape_pasted_image_20110524_220347.png
git rm sketches/jinsuk_ions.png
git rm sketches/jinsuk_ions_mod.pdb
git rm sketches/jinsuk_ions_pdb.py
git rm sketches/jinsuk_ions_with_labels.svg
git rm sketches/mult_chain.jpg
git rm sketches/mult_chain.png
git rm sketches/mult_chain_labeled.png
git rm sketches/mult_chain_labeled.svgz
git rm sketches/multiline_saturation.svgz
git rm sketches/new_lab_cutouts.svg
git rm sketches/newprobe_100629.png
git rm sketches/newprobe_100629_assembly.png
git rm sketches/pressure_cell_dielectric_rod_140513.png
git rm sketches/pressure_cell_taper_140513.png
git rm sketches/qin_cs24_cs19_esr.pdf
git rm sketches/qin_cs24_cs19_esr.svg
git rm sketches/quasi_lens_setup_141023.jpg
git rm sketches/radial_dists.svgz
git rm sketches/radial_dists_w_nearest_neighbor.svgz
git rm sketches/relaxation.svg
git rm sketches/saddle_coil2_130329.jpg
git rm sketches/saddle_coil_130329.jpg
git rm sketches/scope_captures/140326_Deadtime_Config/print_001.png
git rm sketches/scope_captures/140326_Deadtime_Config/print_002.png
git rm sketches/scope_captures/140326_Deadtime_Config/print_003.png
git rm sketches/scope_captures/140326_Deadtime_Config/print_004.png
git rm sketches/scope_captures/140326_Deadtime_Config/print_005.png
git rm sketches/scope_captures/140326_Deadtime_Config/print_006.png
git rm sketches/scope_captures/140326_Deadtime_Config/print_007.png
git rm sketches/scope_captures/140326_Deadtime_Config/print_008.png
git rm sketches/scope_captures/140326_Deadtime_Config/print_009.png
git rm sketches/scope_captures/140326_Deadtime_Config/print_010.png
git rm sketches/scope_captures/140729_ringdown/composite.pdf
git rm sketches/scope_captures/140729_ringdown/composite.svg
git rm sketches/scope_captures/140729_ringdown/composite.xcf
git rm sketches/scope_captures/140729_ringdown/print_003.png
git rm sketches/scope_captures/140729_ringdown/print_004.png
git rm sketches/scope_captures/140729_ringdown/print_005.png
git rm sketches/scope_captures/140729_ringdown/print_006.png
git rm sketches/scope_captures/140729_ringdown/print_007.png
git rm sketches/scope_captures/140729_ringdown/print_008.png
git rm sketches/scope_captures/140729_ringdown/print_009.png
git rm sketches/screenshots/field_export131217.png
git rm sketches/transition_piece.png
git rm sketches/trisha_plan_141023.jpg
git rm sketches/twt_graph.pdf
git rm sketches/twt_graph.svg
git rm sketches/watercell.png
git rm specific/breit_rabi.tex
git rm specific/covariance.tex
git rm specific/dielectric_questions.tex
git rm specific/diffusion_limitation.tex
git rm specific/example_pseudocode_for_thomas.tex
git rm specific/figures/buchner_vesicle_figure.gif
git rm specific/figures/buchner_vesicle_figure.png
git rm specific/figures/cpmg_coh.pdf
git rm specific/figures/cpmg_coh.svg
git rm specific/figures/groes_epr_comparison.pdf
git rm specific/figures/groes_epr_comparison.svgz
git rm specific/figures/groes_incontext.pdf
git rm specific/figures/groes_incontext.svg
git rm specific/figures/groes_incontext.svgz
git rm specific/groes2.tex
git rm specific/klow_math.tex
git rm specific/leakage_vs_relaxivity.tex
git rm specific/marohn_prop.tex
git rm specific/maxwell.tex
git rm specific/parallel_nf.tex
git rm specific/phcyc.tex
git rm specific/probe_airflow_tube.png
git rm specific/read_weil.tex
git rm specific/thermocouple_example.pdf
git rm specific/water_geometry.tex
git rm spreadsheets/090809forbong.xls
git rm spreadsheets/090809forbong_new.xls
git rm spreadsheets/"DNP Setup_forfanucci_jf.xls"
git rm spreadsheets/Ubq_Concentrations_130722_as.xlsx
git rm spreadsheets/acert_orders/Technical_glass_prods_Feb25_2014.xls
git rm spreadsheets/acert_orders/Toner_transfer_141215.xls
git rm spreadsheets/buffer_110406.ods
git rm spreadsheets/comparison_of_radicals.ods
git rm spreadsheets/cost_centers.csv
git rm spreadsheets/dna_120316.ods
git rm spreadsheets/east_shore_claims_140501.xlsx
git rm spreadsheets/flight_calculator.xlsx
git rm spreadsheets/flight_calculator_francks.xlsx
git rm spreadsheets/forqin100312.xls
git rm spreadsheets/freelabel100902.ods
git rm spreadsheets/groes_120905.xlsx
git rm spreadsheets/india_trip_costs.xlsx
git rm spreadsheets/"kstone_Copy of Summary 080911.xls"
git rm spreadsheets/kstone_trimmed_from_080911.csv
git rm spreadsheets/lipidprep100319.ods
git rm spreadsheets/lipidprep100713.ods
git rm spreadsheets/lipidprep100714.ods
git rm spreadsheets/lipidprep100719.ods
git rm spreadsheets/lipidprep100817.ods
git rm spreadsheets/lipidprep100824.ods
git rm spreadsheets/lipidprep100824_forgeorge.xls
git rm spreadsheets/lipidprep100921.ods
git rm spreadsheets/lipidprep101006.ods
git rm spreadsheets/lipidprep110405.ods
git rm spreadsheets/lipidprep110620.ods
git rm spreadsheets/lipidprep120116.ods
git rm spreadsheets/lipidprep120122.ods
git rm spreadsheets/lipidprep120502.ods
git rm spreadsheets/lipidprep120917.ods
git rm spreadsheets/lipidprep120917.xls
git rm spreadsheets/lipidprep121010.ods
git rm spreadsheets/lipids_titration_100303.ods
git rm spreadsheets/lipids_titration_100320.ods
git rm spreadsheets/order_130308.xlsx
git rm spreadsheets/oxotempo091102.xls
git rm spreadsheets/popemca100704.ods
git rm spreadsheets/popemca101103.ods
git rm spreadsheets/popemca110609.ods
git rm spreadsheets/startup_budget.xlsx
git rm spreadsheets/startup_budget_Cornell.xlsx
git rm spreadsheets/startup_budget_RI.xlsx
git rm spreadsheets/turns_adlin_jfmod_120618.ods
git rm spreadsheets/turns_adlin_jfmod_120618.xls
git rm spreadsheets/undergrad_reports.txt
git rm spreadsheets/washu_compiled.xls
git rm spreadsheets/washulist100105.xls
git rm spreadsheets/wedding_schedule.xlsm
git rm spreadsheets/wedding_schedule2.xlsm
git rm spreadsheets/weekplan090909.xls
git rm spreadsheets/weekplan090913.xls
git rm spreadsheets/weekplan090921.xls
git rm spreadsheets/weekplan090928.xls
git rm spreadsheets/weekplan091005.xls
git rm spreadsheets/weekplan091014.xls
git rm spreadsheets/weekplan091020.xls
git rm spreadsheets/weekplan091026.xls
git rm standalone_dopc.py
git rm standalone_integration.py
git rm standalone_integration_forT1.py
git rm structarray_demo.py
git rm summaries/3line.tex
git rm summaries/95GHz_hwstatus.tex
git rm summaries/95_problems.tex
git rm summaries/B1_considerations.tex
git rm summaries/acert_hardware/all_raw_data_traditional_eldor_150114_wtime.pdf
git rm summaries/acert_hardware/sapphire_slices.svg
git rm summaries/acert_hardware/sapphonly_140210.jpg
git rm summaries/acert_hardware/sapphonly_large_halfwave_140214.jpg
git rm summaries/acert_hardware/sapphonly_large_quarterwave_140214.jpg
git rm summaries/acert_hardware/tempo_candy_m100degC.png
git rm summaries/acert_hardware/tempo_candy_m50degC.png
git rm summaries/acert_hardware/tempo_candy_twotemps.svg
git rm summaries/acert_hardware/time_domain,_Sc__traditional_eldor_150114_wtime.pdf
git rm summaries/acert_hardware/time_domain_Scminus.svg
git rm summaries/bio_demo.tex
git rm summaries/figures/Ct_of_fluctuations_deadtime_manybins_140501.pdf
git rm summaries/figures/SNR_vs__T_2_for_echo_ringdown_deadtimevsgain_140428.pdf
git rm summaries/figures/SNR_vs__T_2_for_echo_ringdown_scaleTxpower_140428.pdf
git rm summaries/figures/SNR_vs__T_2_star__for_FID_ringdown_deadtimevsgain_140428.pdf
git rm summaries/figures/SNR_vs__T_2_star__for_FID_ringdown_scaleTxpower_140428.pdf
git rm summaries/figures/all_channels_for_initial_deadtime_decay_140403.pdf
git rm summaries/figures/corrected_amplitudes_for_all_channels_Rx_transfer_140818.pdf
git rm summaries/figures/desired_eldor_signal.svg
git rm summaries/figures/iteration_10_channel_1_Rx_transfer_140818.pdf
git rm summaries/figures/iteration_10_transfer_function_Rx_transfer_140818.pdf
git rm summaries/figures/linear_Tx_atten_140417.pdf
git rm summaries/figures/linear_composite_ringdown_140424.pdf
git rm summaries/figures/linear_rise_time_140430.pdf
git rm summaries/figures/ratio_rise_time_140430.pdf
git rm summaries/figures/separate_rise_time_140430.pdf
git rm summaries/figures/time_domain__Delta_c_1_1__Delta_c_3__1_DBPh_17C_140210.pdf
git rm summaries/figures/time_domain__Delta_c_1_1__Delta_c_3__1_DBPh_17C_140210_edited.svg
git rm summaries/figures/time_variation____weighted_deadtime_manybins_140501.pdf
git rm summaries/hardware_developments.tex
git rm summaries/intro_to_dnp.tex
git rm summaries/library.bib
git rm summaries/md.tex
git rm summaries/mybasiccomments.sty
git rm summaries/mycomments.sty
git rm summaries/mydefs.sty
git rm summaries/myhyperref.sty
git rm summaries/mylabels.sty
git rm summaries/myparagraphformatting.sty
git rm summaries/nddata_expl.tex
git rm summaries/oTP/cw_spectra.svg
git rm summaries/oTP/cw_spectra_highTonly.svg
git rm summaries/old_summaries.tex
git rm summaries/pope.tex
git rm summaries/relaxation_pathways.svg
git rm summaries/test.htm
git rm sunyia_data_141118.ipynb
git rm svn_server_setup.html
git rm teaching_statement.tex
git rm temp.pdf
git rm temp.py
git rm temp2.py
git rm temp_figures/Elevel_toscale.pdf
git rm temp_figures/Elevel_toscale.svg
git rm temp_figures/Emax_110107.pdf
git rm temp_figures/Emax_110107.svg
git rm temp_figures/Emaxdopc_16mM_2p_100728.pdf
git rm temp_figures/Emaxdopc_4mM_5p_100720.pdf
git rm temp_figures/Emaxhydroxytempo_100mM_100916.pdf
git rm temp_figures/Emaxhydroxytempo_150uM_100923.pdf
git rm temp_figures/Emaxpope_ca_4mM_5p_100715.pdf
git rm temp_figures/Evip_110107.pdf
git rm temp_figures/Evip_110107.svg
git rm temp_figures/Evip_110107.svg.bak
git rm temp_figures/Eviphydroxytempo_100mM_100916.pdf
git rm temp_figures/Eviphydroxytempo_150uM_100923.pdf
git rm temp_figures/bargraph110116.pdf
git rm temp_figures/composite_Emax_Evip.pdf
git rm temp_figures/composite_Emax_Evip.png
git rm temp_figures/composite_Emax_Evip.svg
git rm temp_figures/different_probes.pdf
git rm temp_figures/different_probes.png
git rm temp_figures/different_probes.svg
git rm temp_figures/different_probes_wlines.svg
git rm temp_figures/esr_dataset100329_10mM_hn23.pdf
git rm temp_figures/fcr_vs_dnp.pdf
git rm temp_figures/fcr_vs_dnp.svg
git rm temp_figures/filter_library.svg
git rm temp_figures/four_level.png
git rm temp_figures/four_level.svg
git rm temp_figures/linear110102.pdf
git rm temp_figures/log110102.pdf
git rm temp_figures/montecarlo_floatingv_dBmess.pdf
git rm temp_figures/multifitxismaxdopc_16mM_2p_100728.pdf
git rm temp_figures/multifitxismaxdopc_4mM_5p_100720.pdf
git rm temp_figures/multifitxismaxhydroxytempo_100mM_100916.pdf
git rm temp_figures/multifitxismaxhydroxytempo_150uM_100923.pdf
git rm temp_figures/multifitxismaxpope_ca_4mM_5p_100715.pdf
git rm temp_figures/newlinearhydroxytempo_150uM_100923.pdf
git rm temp_figures/newlinearoxotempo10mM_100325.pdf
git rm temp_figures/t10datahydroxytempo_100mM_100916.pdf
git rm temp_figures/t10datahydroxytempo_150uM_100923.pdf
git rm temp_figures/t10datatest101221.pdf
git rm temp_figures/t1vpendor_t10vp110111.pdf
git rm temp_figures/t1vpold_setup_t10vp110111.pdf
git rm temp_figures/temperature_noise.pdf
git rm temp_figures/temperature_noise.svg
git rm temp_figures/temperature_noise_linearized.pdf
git rm temp_figures/temperature_noise_linearized.svg
git rm temp_figures/tempos.cdx
git rm temp_figures/tempos.pdf
git rm temp_figures/tempos.svg
git rm temperature.tex
git rm temperature_outline_sh_jf.docx
git rm temperature_paper.h5
git rm temperatureseries_foradlin.py
git rm test_auto.py
git rm test_code.tex
git rm test_cpmg.py
git rm test_emax.py
git rm test_f90.f90
git rm test_fit.py
git rm test_htlatex/comments_minimal.htm
git rm test_htlatex/test_commentgen.html
git rm test_htlatex/test_commentgen.tex
git rm test_htlatex/test_htlatex.tex
git rm test_integral.py
git rm test_legend.py
git rm test_main_window.py
git rm test_main_window.ui
git rm test_noise.py
git rm test_pytables.py
git rm test_qt.py
git rm testconv.pdf
git rm testplot.pdf
git rm thomas_plots.py
git rm tim/120220_tenative_research_plan.tex
git rm tim/1line_122026.pdf
git rm tim/1lineshiftDAC.pdf
git rm tim/1linespectra_120225.pdf
git rm tim/2line1lines_120226.pdf
git rm tim/2linespectra_120225.pdf
git rm tim/3LineSpec_120225.pdf
git rm tim/3line_120226.pdf
git rm tim/InstBlockDia_SignalTun2.jpg
git rm tim/InstBlockDia_SignalTun2.pdf
git rm tim/TunCurveDAC120225.pdf
git rm tim/whitepaper.tex
git rm tranceiver_test.pdf
git rm tranceiver_test_bad.pdf
git rm transceiver_test.pdf
git rm transceiver_test_fid.pdf
git rm transition_commands.sh
git rm trisha_goals.tex
git rm tuning_curve_130529.py
git rm unseparate_comments.py
git rm viao_specs.txt
git rm vim_settings/.bashrc
git rm vim_settings/.gitconfig
git rm vim_settings/.latexmkrc
git rm vim_settings/.tcshrc
git rm vim_settings/_vimrc
git rm vim_settings/check_numbers.py
git rm vim_settings/colortrans.py
git rm vim_settings/diffwrap.sh
git rm vim_settings/diffwrapper.sh
git rm vim_settings/diffwrapper_text.sh
git rm vim_settings/find_task.sh
git rm vim_settings/folding.vim
git rm vim_settings/ftplugin/bib_latexSuite.vim
git rm vim_settings/ftplugin/latex-suite/bibtex.vim
git rm vim_settings/ftplugin/latex-suite/bibtools.py
git rm vim_settings/ftplugin/latex-suite/brackets.vim
git rm vim_settings/ftplugin/latex-suite/compiler.vim
git rm vim_settings/ftplugin/latex-suite/custommacros.vim
git rm vim_settings/ftplugin/latex-suite/diacritics.vim
git rm vim_settings/ftplugin/latex-suite/dictionaries/SIunits
git rm vim_settings/ftplugin/latex-suite/dictionaries/dictionary
git rm vim_settings/ftplugin/latex-suite/elementmacros.vim
git rm vim_settings/ftplugin/latex-suite/envmacros.vim
git rm vim_settings/ftplugin/latex-suite/folding.vim
git rm vim_settings/ftplugin/latex-suite/macros/example
git rm vim_settings/ftplugin/latex-suite/main.vim
git rm vim_settings/ftplugin/latex-suite/mathmacros-utf.vim
git rm vim_settings/ftplugin/latex-suite/mathmacros.vim
git rm vim_settings/ftplugin/latex-suite/multicompile.vim
git rm vim_settings/ftplugin/latex-suite/outline.py
git rm vim_settings/ftplugin/latex-suite/packages.vim
git rm vim_settings/ftplugin/latex-suite/packages/SIunits
git rm vim_settings/ftplugin/latex-suite/packages/accents
git rm vim_settings/ftplugin/latex-suite/packages/acromake
git rm vim_settings/ftplugin/latex-suite/packages/afterpage
git rm vim_settings/ftplugin/latex-suite/packages/alltt
git rm vim_settings/ftplugin/latex-suite/packages/amsmath
git rm vim_settings/ftplugin/latex-suite/packages/amsthm
git rm vim_settings/ftplugin/latex-suite/packages/amsxtra
git rm vim_settings/ftplugin/latex-suite/packages/arabic
git rm vim_settings/ftplugin/latex-suite/packages/array
git rm vim_settings/ftplugin/latex-suite/packages/babel
git rm vim_settings/ftplugin/latex-suite/packages/bar
git rm vim_settings/ftplugin/latex-suite/packages/bm
git rm vim_settings/ftplugin/latex-suite/packages/bophook
git rm vim_settings/ftplugin/latex-suite/packages/boxedminipage
git rm vim_settings/ftplugin/latex-suite/packages/caption2
git rm vim_settings/ftplugin/latex-suite/packages/cases
git rm vim_settings/ftplugin/latex-suite/packages/ccaption
git rm vim_settings/ftplugin/latex-suite/packages/changebar
git rm vim_settings/ftplugin/latex-suite/packages/chapterbib
git rm vim_settings/ftplugin/latex-suite/packages/cite
git rm vim_settings/ftplugin/latex-suite/packages/color
git rm vim_settings/ftplugin/latex-suite/packages/comma
git rm vim_settings/ftplugin/latex-suite/packages/deleq
git rm vim_settings/ftplugin/latex-suite/packages/drftcite
git rm vim_settings/ftplugin/latex-suite/packages/dropping
git rm vim_settings/ftplugin/latex-suite/packages/enumerate
git rm vim_settings/ftplugin/latex-suite/packages/eqlist
git rm vim_settings/ftplugin/latex-suite/packages/eqparbox
git rm vim_settings/ftplugin/latex-suite/packages/everyshi
git rm vim_settings/ftplugin/latex-suite/packages/exmpl
git rm vim_settings/ftplugin/latex-suite/packages/flafter
git rm vim_settings/ftplugin/latex-suite/packages/float
git rm vim_settings/ftplugin/latex-suite/packages/floatflt
git rm vim_settings/ftplugin/latex-suite/packages/fn2end
git rm vim_settings/ftplugin/latex-suite/packages/footmisc
git rm vim_settings/ftplugin/latex-suite/packages/geometry
git rm vim_settings/ftplugin/latex-suite/packages/german
git rm vim_settings/ftplugin/latex-suite/packages/graphicx
git rm vim_settings/ftplugin/latex-suite/packages/graphpap
git rm vim_settings/ftplugin/latex-suite/packages/harpoon
git rm vim_settings/ftplugin/latex-suite/packages/hhline
git rm vim_settings/ftplugin/latex-suite/packages/histogram
git rm vim_settings/ftplugin/latex-suite/packages/hyperref
git rm vim_settings/ftplugin/latex-suite/packages/ifthen
git rm vim_settings/ftplugin/latex-suite/packages/inputenc
git rm vim_settings/ftplugin/latex-suite/packages/letterspace
git rm vim_settings/ftplugin/latex-suite/packages/lineno
git rm vim_settings/ftplugin/latex-suite/packages/longtable
git rm vim_settings/ftplugin/latex-suite/packages/lscape
git rm vim_settings/ftplugin/latex-suite/packages/manyfoot
git rm vim_settings/ftplugin/latex-suite/packages/moreverb
git rm vim_settings/ftplugin/latex-suite/packages/multibox
git rm vim_settings/ftplugin/latex-suite/packages/multicol
git rm vim_settings/ftplugin/latex-suite/packages/newalg
git rm vim_settings/ftplugin/latex-suite/packages/ngerman
git rm vim_settings/ftplugin/latex-suite/packages/numprint
git rm vim_settings/ftplugin/latex-suite/packages/oldstyle
git rm vim_settings/ftplugin/latex-suite/packages/outliner
git rm vim_settings/ftplugin/latex-suite/packages/overcite
git rm vim_settings/ftplugin/latex-suite/packages/parallel
git rm vim_settings/ftplugin/latex-suite/packages/plain
git rm vim_settings/ftplugin/latex-suite/packages/plates
git rm vim_settings/ftplugin/latex-suite/packages/polski
git rm vim_settings/ftplugin/latex-suite/packages/psgo
git rm vim_settings/ftplugin/latex-suite/packages/schedule
git rm vim_settings/ftplugin/latex-suite/packages/textfit
git rm vim_settings/ftplugin/latex-suite/packages/times
git rm vim_settings/ftplugin/latex-suite/packages/tipa
git rm vim_settings/ftplugin/latex-suite/packages/ulem
git rm vim_settings/ftplugin/latex-suite/packages/url
git rm vim_settings/ftplugin/latex-suite/packages/verbatim
git rm vim_settings/ftplugin/latex-suite/packages/version
git rm vim_settings/ftplugin/latex-suite/projecttemplate.vim
git rm vim_settings/ftplugin/latex-suite/pytools.py
git rm vim_settings/ftplugin/latex-suite/smartspace.vim
git rm vim_settings/ftplugin/latex-suite/templates.vim
git rm vim_settings/ftplugin/latex-suite/templates/IEEEtran.tex
git rm vim_settings/ftplugin/latex-suite/templates/article.tex
git rm vim_settings/ftplugin/latex-suite/templates/report.tex
git rm vim_settings/ftplugin/latex-suite/templates/report_two_column.tex
git rm vim_settings/ftplugin/latex-suite/texmenuconf.vim
git rm vim_settings/ftplugin/latex-suite/texproject.vim
git rm vim_settings/ftplugin/latex-suite/texrc
git rm vim_settings/ftplugin/latex-suite/texviewer.vim
git rm vim_settings/ftplugin/latex-suite/version.vim
git rm vim_settings/ftplugin/latex-suite/wizardfuncs.vim
git rm vim_settings/ftplugin/tex_latexSuite.vim
git rm vim_settings/ftplugin/wiki.vim
git rm vim_settings/ftplugin/wp.vim
git rm vim_settings/fu_franck.vim
git rm vim_settings/git-latexdiff
git rm vim_settings/git-latexdiffnocompile
git rm vim_settings/gvim_command.txt
git rm vim_settings/indent/fortran.vim
git rm vim_settings/indent/tex.vim
git rm vim_settings/latexdiff
git rm vim_settings/mydifftool.sh
git rm vim_settings/myvimrc
git rm vim_settings/plugin/AlignMapsPlugin.vim
git rm vim_settings/plugin/AlignPlugin.vim
git rm vim_settings/plugin/CVSconflict.vim
git rm vim_settings/plugin/SyntaxFolds.vim
git rm vim_settings/plugin/cecutil.vim
git rm vim_settings/plugin/filebrowser.vim
git rm vim_settings/plugin/imaps.vim
git rm vim_settings/plugin/libList.vim
git rm vim_settings/plugin/matchit.vim
git rm vim_settings/plugin/remoteOpen.vim
git rm vim_settings/plugin/surround.vim
git rm vim_settings/resolve_conflicts.sh
git rm vim_settings/resolve_markdone.sh
git rm vim_settings/silentfork.sh
git rm visa_notes.txt
git rm washuinstructions100108.doc
git rm wedding_list.txt
git rm write_comphdr.py
