name: Flake8 Lint

on: [push, pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install flake8-quotes

      - name: Fetch all branches
        run: |
          git fetch --all
          git fetch origin master
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            git fetch origin ${{ github.event.pull_request.head.ref }}
          else
            git fetch origin ${{ github.event.before }}
          fi
          git fetch origin ${{ github.event.after }}
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "$(git branch)" # show the branch names
          fi

      - name: Get changed files
        id: get_changed_files
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            MYCMD="git diff --name-only origin/${{ github.base_ref }}...origin/${{ github.event.pull_request.head.ref }} --diff-filter=AM" 
            echo "$MYCMD"
            echo "$($MYCMD)"
            CHANGED_FILES=$($MYCMD | grep '\.py$' | tr '\n' ' ')
          else
            MYCMD="git diff --name-only ${{ github.event.before }} ${{ github.event.after }} --diff-filter=AM"
            echo "$MYCMD"
            echo "$($MYCMD)"
            CHANGED_FILES=$($MYCMD | grep '\.py$' | tr '\n' ' ')
          fi
          echo "Here are the changed py files:"
          echo "$CHANGED_FILES"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Run Flake8 on changed files
        run: |
          if [ -n "$CHANGED_FILES" ]; then
            echo "Running Flake8 on changed files: $CHANGED_FILES"
            flake8 --inline-quotes='"' --max-line-length=79 --ignore=E203,E225,E226,E231,E261,E265,E293,E302,E305,E306,E401,E731,E741,Q002,W291,W293,W503 $CHANGED_FILES
          else
            echo "No Python files were changed."
          fi
        env:
          CHANGED_FILES: ${{ env.CHANGED_FILES }}
